### ISSUE TITLE
[Bug] video pauses while orientation change & audio level varies; orientation issue

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#100]
1. **[video pauses while orientation change & audio level varies]** _If the user changes the orientation and during the time of that change from portrait to landscape or vice versa, the video suddenly pauses for a second and plays again after properly reaching the orientation. And sometimes, the video gets paused needs to manually play again.
Also, the audio level lowers and regains to the user-defined level again, during this orientation change._

2. **[orientation issue]** _every time I change the iPhone's orientation from portrait to landscape, the orientation doesn't stay fullscreen. if a few-degree angle change or if I place the phone on a flat surface, the orientation changes back to portrait._

ps. I'm hoping to have this fixed soon.

**Comment by arekf** [comment]
Both is not something I can fix now, this is happening due to handling of the system player. It will not be an issue in 1.4.

For 2 you can try option "Lock landscape on rotation" as a partial workaround

> ps. I'm hoping to have this fixed soon.

Then the best option then is fix it yourself. Otherwise you'll have to wait a little 😅
