### ISSUE TITLE
[Enhancement] "Subscriptions" Tab as default homepage if a account is active {homepage customization}

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#103]
Setting the "Subscriptions" Tab as the default homepage if a piped or invidious account is added and made active.

_Example:_ So, this needs to be function similar to the browser homepage if a blank tab or certain webpage is made default, that the "Subscriptions" Tab needs to default until the account is present or remains active.

_**Also, it would be better to make the "Search" Tab as default instead of Favorites if no account is active. Also, the possibility of introducing a toggle or drop-down selector, so the user can customize the setting as needed.**_

**Comment by Insprill** [comment]
Instead of having fixed defaults, it'd be nice to simply have an option for what the default page is.
