### ISSUE TITLE
[Enhancement] video title and following info ~ alignment fix

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#107]
From the image below, you can see the alignment between the video title and the info like uploaded date, views; _**there is the spacing difference if the video title doesn't extend to the new/next line**_.
This needs to be fixed and have it consistent.

_FYI, this issue is present everywhere, not just in the Subscriptions Tab as shown in the image._

![IMG_6529](https://user-images.githubusercontent.com/96393348/160408094-7777785a-aa19-4367-9bad-d43d4a8a21c5.PNG)

**Comment by arekf** [comment]
This actually IS consistent because it keeps the same amount of vertical space for the title, so when video cells are in horizontal (on Favorites page) or on an iPad/Mac/Apple TV where you can see multiple columns then the title and details stay in the same line and video cells are the same height.
