### ISSUE TITLE
[Bug/Enhancement] UI fix needed: inconsistent

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#108]
From Images 1 & 2 below, you can see the UI is not being consistent and this issue/ bug occurs sometimes and sometimes looks okay like in Image 2. This issue happens sometimes when I scroll the page.

### **Image 1:**
![IMG_6530 (Edited)](https://user-images.githubusercontent.com/96393348/160409021-0775fe66-b355-49c6-9fd1-885f5226a238.PNG)

### **Image 2:**
![IMG_6531](https://user-images.githubusercontent.com/96393348/160409083-0f3be1b5-325f-4aa4-858c-1210c6cf72bf.PNG)

**Comment by arekf** [comment]
This is a SwiftUI bug that's unlikely anything can be done about.
