### ISSUE TITLE
search results issue "People also Watched"

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#112]
As you can see from the image shows an "People also watched", which results some problem with displaying the Information.

_Also i think this shouldn't be even seen in yattee as it shows the content scraped by invidious and piped._

_**ps. This issue can be replicated as it appears in every search results of any keywords, need to scroll down a 10-12 videos to see this.**_

![image](https://user-images.githubusercontent.com/96393348/160529033-cbfefb9e-bc67-434d-b0fb-af03c63283c5.png)

**Comment by arekf** [comment]
Same as #109
