### ISSUE TITLE
[bug] Thumbnail not displaying in `Popular` section/tab

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#115]
This 1st video in the Popular Section/tab is the only one having the problem of displaying the thumbnail as I know of, but the video is playable.

![IMG_6541](https://user-images.githubusercontent.com/96393348/161287113-b6bb897c-09b2-4cab-9a00-5498754d5a54.PNG)

**Comment by arekf** [comment]
Cannot reproduce. Is this happening every time to you?

**Comment by bachig26** [comment]
> Cannot reproduce. Is this happening every time to you?

no. I think that one video displayed this issue. now, today's popular section content does show this. I don't know why.
