### ISSUE TITLE
[bug] alignment problem in the `playlist` section/tab

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#116]
If you see the image below, the Playlist Folder name, play button, add option, etc. is having an alignment issue. This suddenly comes to normal when refreshed but if I once again refresh them, this issue arises again.

_**ps. the account name also goes off the screen or lays over the account icon sometimes as in the above issue.**_

![IMG_6540](https://user-images.githubusercontent.com/96393348/161290921-53e05a35-ce7a-4bd9-a5fe-78d39eac3f30.PNG)

**Comment by arekf** [comment]
Fixed in 1.4
