### ISSUE TITLE
[Enhancement] [Apple TV 4K] Settings are very difficult to discover

### ISSUE THREAD

**Issue by Ivan0xFF** [yattee/yattee#119]
The Apple TV 4K remote doesn't have a Menu button, this makes finding the settings almost impossible. For anyone else that struggled for half an hour, you need to long press the Play/Pause button and that will bring up the settings.

Adding a cog icon to the top nav bar, or some other method of getting to the settings would be very appreciated.

**Comment by arekf** [comment]
Solved in v1.4 (56)
