### ISSUE TITLE
[v1.4 alpha 3] Video only reactive to gyroscope once I manually enter and exit full screen with the button

### ISSUE THREAD

**Issue by stripedgoat** [yattee/yattee#121]
As the description says, when I watch a video, and turn around my phone, it doesn't rotate / enter full screen. I have to press the full screen arrows button, and press it once again to exit from full screen, and THEN the gyroscope rotation starts working fine. It needs that nagging with entering/exiting full screen manually before it starts working.

My player settings regarding orientation:

(enabled) Honor orientation lock
(disabled) Lock landscape on rotation
(disabled) Rotate and lock landscape on entering fullscreen

My portrait orientation lock (the iOS option) is disabled.

**UPDATE:**

I had to disable "Lock portrait mode" in the Browsing settings, now it works. So it may not even be a bug afterall. I apologize in that case.

**Comment by arekf** [comment]
Solved in v1.4
