### ISSUE TITLE
[tvOS] Frame Drop when MPV Overlay Active

### ISSUE THREAD

**Issue by allthrowaway** [yattee/yattee#127]
On tvOS, when the new MPV overlay is active/ visible, e.g. right after starting playback, there are noticeable stutters / frame drops.

Tested with a fresh build at `v1.4` `HEAD` on Apple TV 4K (2nd generation), tvOS 15.4.1.

**Comment by arekf** [comment]
Thanks, I am aware of frame drops when controls are visible on tvOS on iOS and also sometimes at the beginning of the video even when controls are not on screen. I'll be debugging this with implementation of next new version of controls.
