### ISSUE TITLE
add `brew install yattee` to Wiki Docs

### ISSUE THREAD

**Issue by GETandSELECT** [yattee/yattee#129]
Hi

I created[ a cask ](https://github.com/Homebrew/homebrew-cask/pull/123026).

I was not able to document `brew install yattee` on this Wiki page https://github.com/yattee/yattee/wiki/Installation-Instructions

Can you please edit this page?

**Comment by arekf** [comment]
I've added it to the docs. Thank you a lot for creating a cask!
