### ISSUE TITLE
Feature requests, improvement ideas

### ISSUE THREAD

**Issue by debpalash** [yattee/yattee#136]
1. Audio Only mode
(Just like piped audio only mode.
UI idea: With an optional floating action button on content page can be enabled disabled from prefs.)

2. Grid view of contents

3. Loading contents faster
(I've noticed the animation is still little laggy after the 1.4 33 release.)

4. Channel profile function on single content page

5. Heating issue while playback (possible high cpu usage in older iPhones eg. 7/+)

6. Fullscreen mode when scrolling down/up for more space for content.

7. Sync/pull instance list from official piped repo. thus the load on Kavin's server can be distributed.

8. Ping time show on the instance list. Ping rate affects performance so it can make faster if user is requesting from nearby instance.

**Comment by arekf** [comment]
> 1. Audio Only mode
>        (Just like piped audio only mode.
>        UI idea: With an optional floating action button on content page can be enabled disabled from prefs.)

Planned for v1.4

>     2. Grid view of contents

Not sure what you mean, can you provide better explanation/mockup?

>     3. Loading contents faster
>        (I've noticed the animation is still little laggy after the 1.4 33 release.)

Which animation? Player controls/animations will be reworked in near future.

>     4. Channel profile function on single content page

Planned but not for near future.

>     5. Heating issue while playback (possible high cpu usage in older iPhones eg. 7/+)
Will be investigated with implementation of new controls, it is likely connected

>     6. Fullscreen mode when scrolling down/up for more space for content.
Do you mean automatic toggling full screen details when you start scrolling?

>     7. Sync/pull instance list from official piped repo. thus the load on Kavin's server can be distributed.

Planned for the future.

>     8. Ping time show on the instance list. Ping rate affects performance so it can make faster if user is requesting from nearby instance.

Good idea, can you open as separate issue? (and for the future please open each idea as separate issue - thanks).
