### ISSUE TITLE
[Enhancement] PiP option from popup menu's

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#137]
From the image below, you may see the options available as in/from popup options when you press and hold the videos/contents.

**_This issue is to request to add an `Open in PiP` directly in the popup menu for easy access._** 

- Mainly, I'm addressing this request from my experience as this will really help in most use case. **One doesn't need to open the video page and put the video in PiP and go back to the other app. This will reduce the few steps and hassle for PiP access.**
 
![image](https://user-images.githubusercontent.com/96393348/169913516-68aebe1d-0149-454a-8e95-f798fc6873f8.png)

**Comment by bachig26** [comment]
this still doesn't work as needed, i tried just now. the video plays as minimized everytime.

**Comment by arekf** [comment]
I tested it on several devices and it works for me. Can you do more tests, check if player switches to AVPlayer, can you open PiP using a button?

**Comment by bachig26** [comment]
> I tested it on several devices and it works for me. Can you do more tests, check if player switches to AVPlayer, can you open PiP using a button?

I just reinstalled the app, it works now at everytime (I tried like ~8-10 videos) I click `Play in PiP`.
And also sometimes, not everytime, the video plays like a second or so at background before PiP opens. I think there is a need for for a slight delay from PiP open and video plays.

**Comment by arekf** [comment]
Yeah, I am aware of the unintended short play, I will fix it hopefully next release. Give me an update if you encounter more issues with opening in PiP.

**Comment by bachig26** [comment]
> Yeah, I am aware of the unintended short play, I will fix it hopefully next release. Give me an update if you encounter more issues with opening in PiP.

Sure. 👍
