### ISSUE TITLE
[tvOS] 4K 60fps Stuttering

### ISSUE THREAD

**Issue by allthrowaway** [yattee/yattee#139]
On an Apple TV 4K (2nd generation) with tvOS 15.5 and v1.4-alpha.4, some 4K 60fps videos exhibit heavy stuttering / frame drops, even when the MPV overlay is not active.

Of course, decoding VP9 @ 4K 60fps is challenging, when this Apple TV doesn't have a VP9 hardware decoder. But both the official YouTube app and Infuse are able to play the same content smoothly, so it should be feasible.

Here's an example: https://www.youtube.com/watch?v=7xbBky_YQdk

**Comment by arekf** [comment]
Thanks for all the issues reported for tvOS, I knew most of them existed as I use tvOS version daily, still good to have them noted down.

Bringing MPV player is a complex process, there's a lot of stuff that need to be implemented manually that was done automatically before by the system player. I will be trying to address those issues as soon as I have time.

**Comment by retrocaster** [comment]
I see regular frame drops in 4k 60fps content on the latest Apple TV 4k (2022 model) with Yattee 1.5.2 (build 195) when using MPV player with either MP4 or WebM.
Given that my $20 Walmart Onn 4k device can play 4k 60fps HDR content in SmartTube with no frame drops, surely there's a way to get the far better Apple TV 4k hardware to do it?

**Comment by stonerl** [comment]
I'm closing this since we changed the default format order. AVC1 is at top and supports hardware decoding.

Besides that there is not much we can do here since it is up to Apple to support AV1 and VP9 Hardware decoding.
