### ISSUE TITLE
[enhancement] Features needed for parity with proprietary YouTube

### ISSUE THREAD

**Issue by slashvalkyrie** [yattee/yattee#146]
Let me say that I definitely appreciate what you're doing here and look forward to being able to use it to replace the rather fugly 1st party implementation, but there are some things missing that prevent this from happening right now. Here's a list of missing features that I can at least remember right now:

- [ ] Recommended section
- [ ] Loop button
- [ ] Chapters support
- [ ] Autoplay
- [ ] History
- [ ] Logging in with Google account
    - [ ] Video uploading
    - [ ] Commenting
    - [ ] Liking
- [ ] Shorts
- [ ] Subscription notifications

**Comment by arekf** [comment]
Hi, thank you for your feedback. 

> Recommended section

Already suggested (#32, #123), will be done in future releases

> Loop button

Added as an issue, maybe can be done along implementation of new player controls

> Chapters support

Already suggested (#91), will be done for next release

> Autoplay

Needs recommendations module, but can be done in future releases, added as an issue

> History

Not sure what you mean, the app saves history of your watches and you can enable in player options to see list of previously played (visible in the queue)

> Logging in with Google account

This is unlikely to ever happen, this app is about keeping privacy first and not connecting with Google at all.

> Shorts

You mean separate UI for listing Shorts? This is not possible without implementation in Invidious/Piped, not sure what's the status of this.

> Subscription notifications

This is unlikely to happen, would require server processing which can cost a lot (both to implement and run later).

If you don't mind, please next time search if there's already an issue with your request and if not open each of them as separate item, that's easier for me to process. Thanks!
