### ISSUE TITLE
Automatic sleep mode while in fullscreen

### ISSUE THREAD

**Issue by AtomHare** [yattee/yattee#148]
Sometimes in fullscreen the phone will start to go in sleep mode.
I'm not sure how to reproduce it sadly

Restarting the app is a temporary fix.

**Comment by stonerl** [comment]
@AtomHare does this still happen?

**Comment by AtomHare** [comment]
I couldn't reproduce it in the latest builds and it looks like no one got similar issues.

We can say that it's most likely fixed!
