### ISSUE TITLE
wrong video date in playlist

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#161]
Chat from [Matrix message](https://matrix.to/#/!cslAxTXdSqYKHOqlbY:matrix.org/$BJsmU6JOhed-xijpAgwh9Q2pPJnMrTPIDtWp3BVrqcI?via=matrix.org&via=thehare.fr&via=radiowarnerd.org)

#### Screenshot
![ima_cd589e0](https://user-images.githubusercontent.com/96393348/172632086-9c1e1b14-3b57-41c5-bb78-982755dc1234.jpeg)

**Comment by DEFCON001** [comment]
Based on what Arkz said in the matrix message, Piped doesn't supply the playlist time, which lines up with 52 years ago (Unix Time 0), so the fix might be to not display time of videos in playlists, or to call the api for release date info on every individual video in the playlist, although that might cause performance issues.
