### ISSUE TITLE
SponsorBlock not working for outros/end of videos (iOS)

### ISSUE THREAD

**Issue by DEFCON001** [yattee/yattee#163]
SponsorBlock doesn't seem to skip outros, they appear in the seek bar (as coloured red), but aren't skipped. I think this might actually have to do with SponsorBlock not skipping sections that go to the end of the video in general, rather than the "outro" subset being the issue, but I haven't found a test case that has an ending that isn't an "outro" yet (or an outro that isn't an ending). 
However SponsorBlock works fine for skipping sections that aren't at the end of videos.

(Note: this doesn't seem to effect intros/skipped segments that start at the beginning of videos, so this seems to be an issue just for endings).

Also, this is a separate issue to #162 which was resolved.

**Comment by DEFCON001** [comment]
The guard section in this submodule from "yattee/main/Model/Player/PlayerSponsorBlock.swift" might be related to the issue, maybe one of the times is rounded at some point or something. Checking the `logger.error()` output will help explain if this is the cause, and possibly what exactly is happening. Is there any way to access said logged output on iOS with the TestFlight version of the app installed, or will we need to use macOS to debug this issue (I don't have access to macOS so this would require someone else to do so)?

```swift
    private func skip(_ segment: Segment, at time: CMTime) {
        guard segment.endTime.seconds <= playerItemDuration?.seconds ?? .infinity else {
            logger.error(
                "segment end time is: \(segment.end) when player item duration is: \(playerItemDuration?.seconds ?? .infinity)"
            )
            return
        }

**Comment by arekf** [comment]
Are you able to provide video where this can be reproduced because I can't?

**Comment by arekf** [comment]
Updated builds have fixed and improved outros skipping - it should close video/skip to next without seeking for the end of video first

**Comment by DEFCON001** [comment]
Thank-you, that fixed it, amazing work like always. Closing issue.
