### ISSUE TITLE
Error trying to use http to invidious

### ISSUE THREAD

**Issue by McMac** [yattee/yattee#168]
Trying to connect to my docker container only using http:

“ Connection failed
The resource could not be loaded because the App Transport Security policy requires the use of a secure conn…”

(No chance to see the full message)

**Comment by arekf** [comment]
Only https is supported at the moment, however I understand the usecase and as it shouldn't be hard to do I'll enable http in next releases

**Comment by arekf** [comment]
@McMac can you try if you can connect to your http docker instance with the latest build?

**Comment by McMac** [comment]
> @McMac can you try if you can connect to your http docker instance with the latest build?

Was able to connect now however none of the preview images of the videos isn't loading. All show exclamation mark. Are they by chance still trying to be loaded via https?

**Comment by arekf** [comment]
@McMac check and let me know what thumbnail URLs are returned from your instance API:
http://instance.address/api/v1/videos/yXohcxCKqvo

You can copy the whole response, or just the URL from `videoThumbnails` part.

**Comment by McMac** [comment]
I am seeing this as an example and if I append this to my instance.address/vi/... I do get the images
`      "videoThumbnails": [
        {
          "quality": "maxres",
          "url": "/vi/QFCMs7prEB8/maxres.jpg",
          "width": 1280,
          "height": 720
        },`

**Comment by McMac** [comment]
BTW, seeing this exclamation mark on iOS and macOS. 
<img width="318" alt="image" src="https://user-images.githubusercontent.com/219912/174600276-bf0f582f-8e27-4836-850a-6bf7cb4915f4.png">

**Comment by GauthierPLM** [comment]
Given how easy HTTPS certificates are to generate today (using Let's Encrypt or similar, or self-signing a cert), is it really a good idea to officially support HTTPS?

**Comment by igniz-** [comment]
This did happen to me, connecting thru https and the issue seems to be that Invidious is returning a relative path so I just fixed it by appending the account url in Model/Applications/InvidiousAPI.swift =>

```
     private func extractThumbnails(from details: JSON) -> [Thumbnail] {
         details["videoThumbnails"].arrayValue.map { json in
-            Thumbnail(url: json["url"].url!, quality: .init(rawValue: json["quality"].string!)!)
+            let url = URL(string: account.url + json["url"].string!)
+            return Thumbnail(url: url!, quality: .init(rawValue: json["quality"].string!)!)
         }
     }
```

But I'm not sure if this is a configuration issue in Invidious as I'm not very familiar with it (also not sure my changes are the best way to fix it, since Swift is by no means my forte). Anyway, maybe this can help someone

**Comment by yur1xpp** [comment]
Do we have an update on this? I'm using HTTP since I'm self hosting a private invidious home server for home use, so there's no need for HTTPS. I can play video just fine, but searching or going to trending all shows blank thumbnails. 

> @McMac check and let me know what thumbnail URLs are returned from your instance API:

This is a response from the API:

```
{
  "type": "video",
  "title": "4 Rules to Help Increase Your Productivity",
  "videoId": "yXohcxCKqvo",
  "videoThumbnails": [
    {
      "quality": "maxres",
      "url": "/vi/yXohcxCKqvo/maxres.jpg",
      "width": 1280,
      "height": 720
    },
    {
      "quality": "maxresdefault",
      "url": "/vi/yXohcxCKqvo/maxresdefault.jpg",
      "width": 1280,
      "height": 720
    },
    {
      "quality": "sddefault",
      "url": "/vi/yXohcxCKqvo/sddefault.jpg",
      "width": 640,
      "height": 480
    },
    {
      "quality": "high",
      "url": "/vi/yXohcxCKqvo/hqdefault.jpg",
      "width": 480,
      "height": 360
    },
    {
      "quality": "medium",
      "url": "/vi/yXohcxCKqvo/mqdefault.jpg",
      "width": 320,
      "height": 180
    },
    {
      "quality": "default",
      "url": "/vi/yXohcxCKqvo/default.jpg",
      "width": 120,
      "height": 90
    },
    {
      "quality": "start",
      "url": "/vi/yXohcxCKqvo/1.jpg",
      "width": 120,
      "height": 90
    },
    {
      "quality": "middle",
      "url": "/vi/yXohcxCKqvo/2.jpg",
      "width": 120,
      "height": 90
    },
    {
      "quality": "end",
      "url": "/vi/yXohcxCKqvo/3.jpg",
      "width": 120,
      "height": 90
    }
  ],
  "storyboards": [
    {
      "url": "/api/v1/storyboards/yXohcxCKqvo?width=48&height=27",
      "templateUrl": "https://i.ytimg.com/sb/yXohcxCKqvo/storyboard3_L0/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiYsNOFBg%3D%3D&sigh=rs%24AOn4CLDPmJ4YChgnHZWu5RruSRzAJL4qIA",
      "width": 48,
      "height": 27,
      "count": 100,
      "interval": 0,
      "storyboardWidth": 10,
      "storyboardHeight": 10,
      "storyboardCount": 1
    },
    {
      "url": "/api/v1/storyboards/yXohcxCKqvo?width=80&height=45",
      "templateUrl": "https://i.ytimg.com/sb/yXohcxCKqvo/storyboard3_L1/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiYsNOFBg%3D%3D&sigh=rs%24AOn4CLA67LwWmfCurCTIlX-pYmmxqW8q3g",
      "width": 80,
      "height": 45,
      "count": 159,
      "interval": 5000,
      "storyboardWidth": 10,
      "storyboardHeight": 10,
      "storyboardCount": 2
    },
    {
      "url": "/api/v1/storyboards/yXohcxCKqvo?width=160&height=90",
      "templateUrl": "https://i.ytimg.com/sb/yXohcxCKqvo/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiYsNOFBg%3D%3D&sigh=rs%24AOn4CLC1C0ytBpm0kZcb1mVwUv20XZXSvw",
      "width": 160,
      "height": 90,
      "count": 159,
      "interval": 5000,
      "storyboardWidth": 5,
      "storyboardHeight": 5,
      "storyboardCount": 7
    }
  ],
  "description": "Go to https://squarespace.com/mattdavella to save 10% off your first purchase of a website or domain using code MATTDAVELLA. Thanks to Squarespace for sponsoring this vid!\n\n💯 You can also follow me here:\nNewsletter:  http://mattdavella.com\nIG:  http://instagram.com/mattdavella\nTwitter:  http://twitter.com/mattdavella\nPodcast:  http://groundupshow.com\n\n❤️ Get more videos & support my work:\nhttp://patreon.com/mattdavella\n\nThanks for watching!",
  "descriptionHtml": "Go to <a href=\"https://squarespace.com/mattdavella\">squarespace.com/mattdavella</a> to save 10% off your first purchase of a website or domain using code MATTDAVELLA. Thanks to Squarespace for sponsoring this vid!\n\n💯 You can also follow me here:\nNewsletter:  <a href=\"http://mattdavella.com/\">mattdavella.com/</a>\nIG:  <a href=\"http://instagram.com/mattdavella\">instagram.com/mattdavella</a>\nTwitter:  <a href=\"http://twitter.com/mattdavella\">twitter.com/mattdavella</a>\nPodcast:  <a href=\"http://groundupshow.com/\">groundupshow.com/</a>\n\n❤️ Get more videos & support my work:\n<a href=\"http://patreon.com/mattdavella\">patreon.com/mattdavella</a>\n\nThanks for watching",
  "published": 1622419200,
  "publishedText": "2 years ago",
  "keywords": [],
  "viewCount": 707553,
  "likeCount": 31156,
  "dislikeCount": 0,
  "paid": false,
  "premium": false,
  "isFamilyFriendly": true,
  "allowedRegions": [
.
.
.
```

**Comment by agail** [comment]
@McMac @yur1xpp @igniz- 

Installed Invidious and Yattee (TvOs) a while back ago. Like you probably experienced, thumbnails shows correctly when using a browser (http-only), but not while using Yattee.

Reading [the Yattee FAQ says](https://github.com/yattee/yattee/wiki/FAQ) suggests checking that thumbnails URLs are being generated by the API (videoThumbnails key).

If it is not the case, check your Invidious instance settings, you should set the following values when using with **https**:
_Turns out this applies for unencrypted hosted invidious as well._

```
domain: your.instance.com
external_port: 443
```
I revisited the [documentation for docker compose](https://docs.invidious.io/installation/#docker-compose-method-production)
Keeping everything default except for hmac_key, I adjusted the yml-file to include domain and external_port as below.

_I'm running a nginx-reverse proxy in front of docker, invidious.home.arpa**_
```
domain: invidious.home.arpa
external_port: 80
```
** invidious_proxy.conf
```
server {
    listen      80;
    server_name invidious.home.arpa;
    
    location / {
        access_log              /var/log/nginx/invidious_access.log;
        error_log               /var/log/nginx/invidious_error.log;

        proxy_pass              http://127.0.0.1:3000;
        proxy_buffering         off;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-Host $host;
        proxy_set_header        X-Forwarded-Port $server_port;
    }
}
```

**Comment by yur1xpp** [comment]
@agail thanks for tagging me. Indeed, it does work. I just simple set the domain to `domain: 192.168.x.x` and thumbnails now loads on HTTP.

**Comment by stonerl** [comment]
Since this seems to be fixed, I'm closing this one.
