### ISSUE TITLE
App crash on subscription page

### ISSUE THREAD

**Issue by hellojaccc** [yattee/yattee#172]
it crashes when i open subscription, and trending.

No matter which instance/account. Both crashes on piped and invidiohs

**Comment by arekf** [comment]
Please check if the most recent build fixed it, if not [attach crash report](https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs#Locate-Crash-Reports-and-Memory-Logs-on-the-Device) and reopen the issue.
