### ISSUE TITLE
[Bug] Play/Pause button issue in mpv

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#173]
My message from Matrix Channel: https://matrix.to/#/!cslAxTXdSqYKHOqlbY:matrix.org/$ZAKknoPNtv5tuW88AbKZWUSgY6sl7GFEPIabpzMxZ4A?via=matrix.org&via=thehare.fr&via=radiowarnerd.org

When I use Siri during the playback, the video gets paused but the button still stays on showing the pause button, and need to manually press twice to play again.

This Play/Pause button issue also occurs if I went to the home screen while playing and reopen the background yattee, the pause button still shows for pausing the video but the video is already paused. so I need to press the button twice again to play the content.

_ps. I don't know which other situation this might occur as this issue is based on my usage._

**Comment by arekf** [comment]
I believe it should be resolved in recent builds, you can let me know if you notice it again and I'll reopen
