### ISSUE TITLE
Adding videos to a playlist takes about 4 seconds to add.

### ISSUE THREAD

**Issue by chadify** [yattee/yattee#177]
It'd be great if the adding time is improved. 

Also can you add an option to add a video to most recent/active playlist, for a quick add.

_Adding the most recent option in the context menu_
![image](https://user-images.githubusercontent.com/72332949/174668183-d9a9bca8-18bf-4ccf-85d3-7f14364e9acb.png)

**Comment by arekf** [comment]
Fixed in v1.4 (56)
