### ISSUE TITLE
[Bug] Not able to add playlist

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#178]
When I try to add a video to the playlist, I'm seeing an some error like:

**`Error when accessing playlist`**
`(500) Internal server error`

This error message shows on both the Piped and Invidious.

**Comment by arekf** [comment]
@bachig26 Is this still relevant? Server error is, as said, server side so I need more details on the instance. Works for me with default Piped instance

**Comment by bachig26** [comment]
> @bachig26 Is this still relevant? Server error is, as said, server side so I need more details on the instance. Works for me with default Piped instance

I tried just now again, this error seems to be not happening at the moment. I'm not sure, maybe if this happens again I'll try to input more details.
Also, you can close this if you want and I can open a new issue when find this again if it's okay for you.
