### ISSUE TITLE
Support PeerTube

### ISSUE THREAD

**Issue by xplosionmind** [yattee/yattee#180]
It would be great if the app could seamlessly be integrated with [PeerTube](https://joinpeertube.org 'Join PeerTube')

**Comment by bachig26** [comment]
> It would be great if the app could seamlessly be integrated with [PeerTube](https://joinpeertube.org)

I think the API structure is completely different and it might need a lot of effort to implement, also it might need complete rework/rewrite of the app.

And also I don’t know if the implementation of PeerTube is suitable or necessary for yattee.
