### ISSUE TITLE
Enable adding the videos in the related section to playlists. 

### ISSUE THREAD

**Issue by chadify** [yattee/yattee#181]
Currently there are only two options. Add the playlist option as well.

![5B3E8372-F85D-4EC7-8D38-364D142495E7](https://user-images.githubusercontent.com/72332949/174788411-3f4be7aa-6caf-4d6a-a8e1-1b337497cbe5.png)

**Comment by bachig26** [comment]
> Currently there are only two options. Add the playlist option as well.

FYI, the **_Play Next_** and **_Play Last_** is particularly for adding the videos in the Queue, as how you want the video to be played in the queue, and it’s not relevant for the Playlist addition.

**Comment by chadify** [comment]
@bachig26 No, what I meant was to add a third option, just like in the youtube app, to add the videos appeaing in the related section to any desired playlist, for example the Watch Later playlist.

**Comment by arekf** [comment]
Added in v1.4 (56)
