### ISSUE TITLE
v1.4-alpha.5 is not available on updates feed for macOS

### ISSUE THREAD

**Issue by goodness-from-me** [yattee/yattee#183]
Hello.
Seems like [v1.4-alpha.5](https://github.com/yattee/yattee/releases/tag/v1.4-alpha.5) is not published to updates feed for macOS and client doesn't detect new version available.

**Comment by arekf** [comment]
Sorry for that, I had to remove update framework from the latest builds to be able to push it into TestFlight. I'll try to bring it back in next releases.
