### ISSUE TITLE
[Feature Request] Player option to minimize video info page when in PiP

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#186]
#### Current Behaviour:

When PiP is enabled for a video in fullscreen or within the video page, the video plays in PiP but the video's info page still open and need to swipe down them to minize it before interacting with other menus like search to look for other if needed.

#### Expected Behaviour:

I'm hoping to have an option under the Player settings, so that user can keep the current action like I described above in "Current Behaviour" or to minimize the video info page and just to view the content in PiP.

This way one can have some option on how the PiP works like current default way or similar to Play in PiP way.

In my case, I put the video in PiP and try explore other contents, so this option will help to reduce the few swipes and time.

**Comment by arekf** [comment]
This was added in previous biuilds
