### ISSUE TITLE
Uncomfortably small player UI on iPad

### ISSUE THREAD

**Issue by martin-desktops** [yattee/yattee#195]
Using the 59 TestFlight build with the new player is a bit frustrating experience on iPad because of much smaller UI elements in video player. I included screenshots from Yattee and Apple TV for comparison.
![A0A04A29-AD25-4E84-BA62-A6E9A50E5333](https://user-images.githubusercontent.com/64419373/176150527-8cb0c55e-95e8-4fee-8a0d-6a1d85d37b29.png)
![ACAEE9E9-7CA4-49CC-8EFF-487A3469B070](https://user-images.githubusercontent.com/64419373/176150577-2035e8a1-e1f1-4fc4-8435-fb31a0dafb72.png)

**Comment by arekf** [comment]
Cześć 😄 

As you can see the controls are still a work in progress. I am aware it's not yet suitable for all the screens and I want to bring customization options so you will be able to choose buttons/size of your liking, but you need to wait (and suffer a little 😉) until then.

**Comment by arekf** [comment]
Latest build includes size options for controls, I think we can close this issue
