### ISSUE TITLE
`sudden/one time` fullscreen portrait mode bug (see screenshot)

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#200]
As you can see in the image, I got this sudden fullscreen type portrait mode that I got earlier as this mode is not available yet and the player controls are overlapped on the video content and doesn't look like the native AVPlayer fullscreen portrait mode.

_ps. This is definitely an bug as this doesn't happen again when I tried and wanted to express the opinion as I opened an issue for the portrait mode in fullscreen similar to AVPlayer yesterday because this kind of portrait mode (from the image) is not look good as it covers the contents completely._

#### Screenshot
![IMG_0110](https://user-images.githubusercontent.com/96393348/176322936-79cc8171-f0a7-45e1-88b3-f061e4b3ee98.PNG)

**Comment by arekf** [comment]
Closing as full screen portrait is being added
