### ISSUE TITLE
[Feature Request] Tapping on buttons on the bar makes it go back to the start.

### ISSUE THREAD

**Issue by chadify** [yattee/yattee#206]
Make such that tapping on the subscription, trending etc. button on the tab bar makes jump back to the start of the page.

**Comment by bachig26** [comment]
> Make such that tapping on the subscription, trending etc. button on the tab bar makes jump back to the start of the page.

This will not be possible as this function is already available as apple default feature, if you tap the Notification Center (the top where the battery, time shows) this takes you to the start or top of the current page.

**Comment by arekf** [comment]
I don't understand why this is not enabled in native SwiftUI tab view component while Apple seems to be doing it in their own apps. I remember trying to find a way to do it once but it was hard, maybe I'll check if something change since then.

**Comment by bachig26** [comment]
@arekf I just remembered this function is also enabled in iOS WhatsApp, I know it’s not open source but want to let you know.
