### ISSUE TITLE
[Enhancement] Skip loading the sponsor part of a video and auto load the subsequent part.

### ISSUE THREAD

**Issue by chadify** [yattee/yattee#207]
As the sponsor part is automatically going to get skipped. Make mpv not load the sponsor part and instead jump on loading the next part, so the transition is smooth without any buffering/hiccups.

**Comment by arekf** [comment]
This has been improved in way that now mpv buffers 2 minutes of videos so skipping most of segments should be immediate. I checked but it looks like there's no way to tell mpv to skip buffering/displaying specific part of video.
