### ISSUE TITLE
tvOS bug and enhancement for 1.4 and 1.3

### ISSUE THREAD

**Issue by hommegithub** [yattee/yattee#208]
Thanks for making the tvOS fix a priority!
- Older remotes still not working fully in 1.4 (tested on ATV HD with tvOS 16), a player control shows and is able to select
- playback speed changed (tempo) again without any confirmation and for no reason...
- Player control is way too small visually to be useful.
- Invidious not working at all, takes forever to play any streams.
captions/subtitles are completely gone, both indivious and piped.
- latest build started crashing on my ATV HD (didn't happen on previous 1.4 builds)

Suggestions:
- both 1.4 and 1.3: options to "play all" for subscriptions, or parse subscription feed onto a playlist. Or option to add all onto a new playlist (user creates a new list everytime which is not ideal).

Please maintain v1.3 as this seems to work best with older ATVs and the apple standard player UI
- any chance to default 1080p quality?
- Subtitles/closed captioning has missing auto-generated English option (not sure if it's a 3rd party YouTube limitation)
- Subtitles/closed captioning options on yattee UI?
- changing streaming quality no longer works (used to work with adaptive HLS as default as this would load subtitles, then I choose 1080p manually on each video)

P.S. Just wanted to stressed that a lightweight solution like Yattee seems to be the last hope for tvOS, I have Kodi but maintaining it is another nightmare.

One more point: I have only recently added invidious instance, could anyone confirm this would mess up yattee having both piped and invidious instances stored? Both 1.4 and 1.3...

**Comment by arekf** [comment]
> - Older remotes still not working fully in 1.4 (tested on ATV HD with tvOS 16), a player control shows and is able to select

Please explain what do you mean by "not working fully".

> - playback speed changed (tempo) again without any confirmation and for no reason...

That is unheard of. Are you sure it's changing playback rate and it's not stuttering because of performance problems?

> - Player control is way too small visually to be useful.

The current controls are shared from iOS/Mac version. I will be working on proper layout for TV screen in future builds. I will not be updating those current controls for Apple TV needs.

> - Invidious not working at all, takes forever to play any streams.

Are you using public instance? If yes, which one? I am using the app with both Piped and Invidious at the same time and there shouldn't be any issue with that.

> captions/subtitles are completely gone, both indivious and piped.

1.4 does not support subtitles at the moment, it will be coming back soon.

> - latest build started crashing on my ATV HD (didn't happen on previous 1.4 builds)

Is it crashing on any specific action?

> Suggestions:
> 
> - both 1.4 and 1.3: options to "play all" for subscriptions, or parse subscription feed onto a playlist. Or option to add all onto a new playlist (user creates a new list everytime which is not ideal).

This is planned after 1.4 release.

> 
> Please maintain v1.3 as this seems to work best with older ATVs and the apple standard player UI

I will not be maintaining v1.3 after 1.4 is released. Although I will bring to 1.4 an option to switch to system player so it should make no difference.

> - any chance to default 1080p quality?

System player needs to download entire file for 1080p so that would make you wait a lot before anything can start playing.

> - Subtitles/closed captioning has missing auto-generated English option (not sure if it's a 3rd party YouTube limitation)
> - Subtitles/closed captioning options on yattee UI?

I am not sure either, I will check while I will be implementing subtitles for 1.4. 

> - changing streaming quality no longer works (used to work with adaptive HLS as default as this would load subtitles, then I choose 1080p manually on each video)

It always had those issues, those file formats that YT provides are just not the best for the system player. I'll try to find out if anything can be done on that once I bring back system player to 1.4.

> P.S. Just wanted to stressed that a lightweight solution like Yattee seems to be the last hope for tvOS, I have Kodi but maintaining it is another nightmare.

And I am committed to maintaining it for the future, you need to wait for it to get polished, you can see it's being slowly improved. 

> One more point: I have only recently added invidious instance, could anyone confirm this would mess up yattee having both piped and invidious instances stored? Both 1.4 and 1.3...

This should not be an issue. What do you mean by "mess up"? What problems it causes for you?

**Comment by hommegithub** [comment]
(Placeholder and WIP)

I did some further testing with piped, invidious - their account level (using safari browser)
Then with Yatte on iOS vs tvOS with those accounts and will provide updated feedback.

In a nutshell Invidious seem to work best for my use cases (I have legacy iOS 6.x devices which still works natively with safari) while loading cc/subtitles on the right public instance - ymmv so I'm not gonna name it.

Invidious also works with Yatte on iOS 15/16 thus far.

Now problem with Yatte 1.4 tvOS 16 (on ATV 3/HD) -

Control panel not proportionate. 
Cc not yet suoported

**Comment by hommegithub** [comment]
[WIP]

I did some further testing with piped, invidious - their account level (using safari browser)
Then with Yatte on iOS vs tvOS with those accounts with updated feedback.

In a nutshell Invidious seem to work best for my use cases (I have legacy iOS 6.x devices which still works natively with safari) while loading cc/subtitles on the right public instance - ymmv so I'm not gonna name it.

Invidious also works with Yatte on iOS 15/16 thus far and tvOS (kinda? not with 1.3)

### The good about Yattee 1.4 tvOS 16 (on ATV 3/HD)
- Playlist syncs between Invidious on Safari, Yattee iOS and tvOS (thank god!)
- Subscriptions feed shows reliability

Now problem with Yatte 1.4 tvOS 16 (on ATV 3/HD) - I ditched Piped (https://github.com/TeamPiped/Piped/issues/1193)
**Control panel - t**hat seem to be my reasoning for preferring 1.3 (tvOS behaves differently so overlay control panel won't play well with non touch screen devices no matter what?) and most likely won't work with iOS connected with ATV now playing/remote/homekit controlling ATV.

> > * Older remotes still not working fully in 1.4 (tested on ATV HD with tvOS 16), a player control shows and is able to select
> 
> Please explain what do you mean by "not working fully".
> 
> > * playback speed changed (tempo) again without any confirmation and for no reason...
> 
> That is unheard of. Are you sure it's changing playback rate and it's not stuttering because of performance problems?
> 
> > * Player control is way too small visually to be useful.
> 
> The current controls are shared from iOS/Mac version. I will be working on proper layout for TV screen in future builds. I will not be updating those current controls for Apple TV needs.
> 
> > * Invidious not working at all, takes forever to play any streams.
> 
> Are you using public instance? If yes, which one? I am using the app with both Piped and Invidious at the same time and there shouldn't be any issue with that.
> 
> > captions/subtitles are completely gone, both indivious and piped.
> 
> 1.4 does not support subtitles at the moment, it will be coming back soon.
> 
> > * latest build started crashing on my ATV HD (didn't happen on previous 1.4 builds)
> 
> Is it crashing on any specific action?
> 
> > Suggestions:
> > 
> > * both 1.4 and 1.3: options to "play all" for subscriptions, or parse subscription feed onto a playlist. Or option to add all onto a new playlist (user creates a new list everytime which is not ideal).
> 
> This is planned after 1.4 release.
> 
> > Please maintain v1.3 as this seems to work best with older ATVs and the apple standard player UI
> 
> I will not be maintaining v1.3 after 1.4 is released. Although I will bring to 1.4 an option to switch to system player so it should make no difference.
> 
> > * any chance to default 1080p quality?
> 
> System player needs to download entire file for 1080p so that would make you wait a lot before anything can start playing.
> 
> > * Subtitles/closed captioning has missing auto-generated English option (not sure if it's a 3rd party YouTube limitation)
> > * Subtitles/closed captioning options on yattee UI?
> 
> I am not sure either, I will check while I will be implementing subtitles for 1.4.
> 
> > * changing streaming quality no longer works (used to work with adaptive HLS as default as this would load subtitles, then I choose 1080p manually on each video)
> 
> It always had those issues, those file formats that YT provides are just not the best for the system player. I'll try to find out if anything can be done on that once I bring back system player to 1.4.
> 
> > P.S. Just wanted to stressed that a lightweight solution like Yattee seems to be the last hope for tvOS, I have Kodi but maintaining it is another nightmare.
> 
> And I am committed to maintaining it for the future, you need to wait for it to get polished, you can see it's being slowly improved.
> 
> > One more point: I have only recently added invidious instance, could anyone confirm this would mess up yattee having both piped and invidious instances stored? Both 1.4 and 1.3...
> 
> This should not be an issue. What do you mean by "mess up"? What problems it causes for you?

**Comment by stonerl** [comment]
@hommegithub can we close this one since it is almost two years old? If some issues are still there or resurface, open new issues. But please only one issue per bug/enhancement.
