### ISSUE TITLE
Typing in search bar is slow 

### ISSUE THREAD

**Issue by UnixPhonez** [yattee/yattee#209]
When typing in the Yattee search bar for videos it’s slow seems super slow 

device:
iPhone X 
15.5

**Comment by arekf** [comment]
Search performance has been improved throughout recent builds, I think it's ok to close this now

**Comment by LennyPenny** [comment]
I disagree, as soon auto suggestions pop it goes slow again - I guess they are blocking somehow

**Comment by arekf** [comment]
> I disagree, as soon as suggestions pop it goes slow again - I guess they are blocking the text input somehow

I cannot reproduce that. Please add device, system version and possibly screen recording because I don't understand where's the issue now.

**Comment by LennyPenny** [comment]
iphone X ios 15

- https://user-images.githubusercontent.com/4027243/190182139-f1096c2e-a629-427e-a9eb-a46575b34bef.MOV

typing speed was about constant but after the "very" there started to be a ~1s delay

**Comment by arekf** [comment]
@LennyPenny @UnixPhonez could you check if 1.4.2 got it fixed for you too?

**Comment by lenny-optiopay** [comment]
yes its working perfectly now!

**Comment by LennyPenny** [comment]
Yes it's working perfectly now!

**Comment by arekf** [comment]
Great, closing it for now then.
