### ISSUE TITLE
Advanced settings text alignment issue

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#213]
As you can see in the image below from the build 66, there seems to a bug to the alignment of the text.

#### Screenshot

![ima_fd78846](https://user-images.githubusercontent.com/96393348/177020383-71a821be-3269-4e97-a515-bbe4ef692422.png)

**Comment by bachig26** [comment]
@arekf This [above commit](https://github.com/yattee/yattee/commit/82a354d9beb1915aac4eb3c65f2937601e1dacdd) still didn't completely solve this issue.


#### Screenshot
![IMG_6596](https://user-images.githubusercontent.com/96393348/177063114-5e1f7a15-6f06-4a07-a695-578d0210b8a2.PNG)

**Comment by arekf** [comment]
This screen will be eventually replaced with a more complex one for more options and I'll change it then. BTW my SE renders "settings above" in the same line, not sure why it's not doing it on your screen.
