### ISSUE TITLE
improve/fix portrait thumbnail

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#218]
currently the portrait thumbnails are stretched and needs an improvement in fixing it.

#### Screenshot
![481D16BB-0C39-470F-BFF0-FD406EF3D2E0](https://user-images.githubusercontent.com/96393348/177168297-a7340bb3-bd91-46d0-940b-c215af5be1a7.jpeg)

_ps: this issue is only present with the Piped instances. I don’t know if this is a API or App issue._

**Comment by UnixPhonez** [comment]
happens to all #Short videos

**Comment by Johnny5sword** [comment]
<img width="375" alt="IMG_5360" src="https://user-images.githubusercontent.com/112535244/198836260-abb8fa0d-a721-46a9-a531-35af13937fd8.PNG">

It seems fine for me now. Is this still an issue for others?
I'm using a Piped instance btw.
