### ISSUE TITLE
fix channel name in channel view

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#219]
The channel name is proper while viewing the channel, as the name gets overlapped by the subscribers count. 

This needs to fixed to adjust the channel name and subscribers count.

#### Screenshot
![859D0DA7-69CC-4F5B-83CD-D63EC65992F2](https://user-images.githubusercontent.com/96393348/177168681-a998886e-8f8e-441e-b76c-f86ddb760beb.jpeg)

_ps: approx. after 2 hrs I just found that there are no channel names visible for other channels except the one from the screenshot. I think this might be an bug and I’m connected to a Piped instance during the screenshot, this issue is not available in Invidious. 
I think there is some consistency issue between both API output. I don’t know if this API issue or app issue._

**Comment by arekf** [comment]
Fixed in build 85
