### ISSUE TITLE
additional improvements to Public Locations option

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#220]
1. If you see in the _**below image**_, when I select the location as “Greece” and clicked the “Switch to public locations”, it jumps to a public location but not the selected country.

2. I just used this option few times and found that when I select a location, it doesn’t count automatically to the instance instead I need to click the “Switch to public locations”. I don’t if this is possible, but it would nice to have connect when selecting the location. (SWITCH TO OTHER PUBLIC LOCATION is okay, but needs to be within the selected location).

3. Also it would be good to have the “Switch to Public Location” in the “Select Account” option at Home/Main page.

#### Screenshot
![5EBD9219-3C2D-4F4C-A18E-E78D2A0A0846](https://user-images.githubusercontent.com/96393348/177169457-13d07484-dde6-41d8-a377-3fa725d61d27.jpeg)

**Comment by arekf** [comment]
1. Most of the countries have only 1 location so it tries to change to switch you to other instance of your region. This option is supposed to be used in exceptional cases.
2. It's expected, you should be able to switch country of public locations without switching to it.
3. You have it as long as you don't select "Don't use public locations".
