### ISSUE TITLE
TestFlight beta is full

### ISSUE THREAD

**Issue by baerni** [yattee/yattee#223]
Can you increase the number of testers? On testflight there is information that beta is full.

**Comment by arekf** [comment]
TestFlight has limited number of 10k testers allowed which we're close to reach. I'm releasing small number of seats every few days. Just opened it, hope you can join it before it's gone.

**Comment by marcocce** [comment]
> Can you increase the number of testers? On testflight there is information that beta is full.

I understand you man... I've been trying to get in for months but nothing :(

**Comment by DEFCON001** [comment]
Hopefully if the EU forces apple to have a *usable* third party app store (the altstore is a mess and not useable for non technical users, plus requiring a pc for app installs and updates is a pain), this should get easier.
