### ISSUE TITLE
add option `Number of videos shown in feed` for subscriptions

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#225]
There is a option for Invidious Instance: Number of videos shown in feed for subscriptions and I think it will be a good one to have in the settings.

**Comment by suymur** [comment]
Duplicate of #301 
> EDIT: If you go to your account settings in Invidious there is an option called "Number of videos to show in feed" I set this to 1000 and the issue is resolved.

This solved it for me...!

**Comment by stonerl** [comment]
@bachig26  There is an option in Yattee's Advanced section called Maximum feed items. I guess this is what you where asking for.
