### ISSUE TITLE
conflict between enter/return and auto-suggestion

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#230]
See image below: When I was typing the word like "toas" for "toast" and if see the word "toss" in keyboard auto-suggestion, if I press `enter/return` key the toss should be replaced which is as expected **but when I select the word "toast" from the app search suggestion, that word "toast should be used" instead it replaces with the keyboard auto-suggestion**. 

I don't know if this a bug or something but I think I'm seeing this problem only with yattee.

#### Screenshot
![IMG_0134](https://user-images.githubusercontent.com/96393348/178103306-d4021fb0-5613-48c5-afbb-0ea8a14f11a9.PNG)

**Comment by stonerl** [comment]
I am not sure if I understand this correctly, but autocorrect has been disabled for the search field. So I'm closing this one
