### ISSUE TITLE
aspect ratio auto crops when opening minimized (build 72)

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#235]
When the player in full screen either in portrait or landscape, after opening the app from its minimized state, the video gets cropped.

ps. This crop doesn’t happen frequently but noticeable at times.

**Comment by bachig26** [comment]
> Cannot reproduce. Device and video recording please.

This above mentioned crop issue, I couldn't reproduce again after few tries and I'll post it after few days and I experienced again, I forgot to make a recording of it.

Also during the process of trying to reproduce it, I found another bug or something, which I have attached below with images and clip.

Device: iPhone SE 3rd Gen (2022) | iOS: 15.5

This issue happens everytime, like when I minimize a fullscreened video and opening via the control/notification center player option.

I can't view the player instead the video info is there and as you can see that I can only see and access the subscriptions page behind and the player is completely gone.

#### Screenshot
Before minimizing the app:
![IMG_0141](https://user-images.githubusercontent.com/96393348/178371694-3660e11f-65e2-4840-b69f-8c764d7e0425.PNG)

After opening via control/notification center player option:
![IMG_0142](https://user-images.githubusercontent.com/96393348/178371736-89d9ea86-61ff-4705-8c98-1e5746f1822b.PNG)


#### Clip [clip is around 12MB and I couldn't upload it without zipping it.]
[RPReplay_Final1657574829.zip](https://github.com/yattee/yattee/files/9088010/RPReplay_Final1657574829.zip)

**Comment by arekf** [comment]
This should be fixed in current 1.4 build. Closing, please reopen in case you'd notice it again.
