### ISSUE TITLE
misplacement of player overlay settings (build 72)

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#236]
The player overlay settings as you can see in the image is misplaced and also when opening the settings the other controls gets hidden.

#### Screenshot
1. PORTRAIT
![335568F5-99DC-44F4-9A1B-191CAAB8B6DD](https://user-images.githubusercontent.com/96393348/178343696-ddc15096-a061-4b66-8926-c68876b226ab.png)

2. LANDSCAPE
![3E26B82C-F319-463C-835C-BEF31167C234](https://user-images.githubusercontent.com/96393348/178344148-b1e427c0-3f66-4877-99b0-1ebb4486b199.png)

**Comment by arekf** [comment]
None of this is unplanned, this view will be updates soon.
