### ISSUE TITLE
Subscription Tab disappearing

### ISSUE THREAD

**Issue by GAMZPRISM2** [yattee/yattee#239]
Subscription tab disappearing regularly, and can only be regained by disabling the section under browsing in settings.

**Comment by arekf** [comment]
The subscriptions section won't show up if it cannot be retrieved from the instance. Piped is undergoing issues causing subscriptions to stop working quite often, it's not something I can fix. You can check if you can open the feed in your web browser, if it cannot be loaded there it means it won't show up in the app. If it's showing in the web browser but not in the app then it's a bug and let me know in that case and I can reopen the issue.
