### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by UnixPhonez** [yattee/yattee#243]
Make yattee support PWA for iOS devices including iPhones & iPads similar to how revolt.chat does their pwa support for their discord alternative platform

**Comment by arekf** [comment]
I don't understand what you mean. The app already has a layout for iPhone with tab navigation and other one for iPad with sidebar navigation.

**Comment by UnixPhonez** [comment]
> I don't understand what you mean. The app already has a layout for iPhone with tab navigation and other one for iPad with sidebar navigation.

I'm talking about Progressive Web Apps, this came to my mind due to the matrix server as someone stated that yattee may not get apples app store approval so this is an alternative if yattee were to get denied

**Comment by arekf** [comment]
The point of this app is is to have native, non-browser experience. Both Invidious and Piped already have their web front-end. This would require to create completely new project from scratch, we can't use existing native app components. Many things are not possible to do in web apps. I am just not interested in doing that. 

I don't know yet if this will be allowed in the App Store as I haven't tried to get the approval yet. I will be trying though and I have few ideas how to make it passable.

**Comment by UnixPhonez** [comment]
> The point of this app is is to have native, non-browser experience. Both Invidious and Piped already have their web front-end. This would require to create completely new project from scratch, we can't use existing native app components. Many things are not possible to do in web apps. I am just not interested in doing that.
> 
> I don't know yet if this will be allowed in the App Store as I haven't tried to get the approval yet. I will be trying though and I have few ideas how to make it passable.

understandable just wanted to throw it out their and i wish you luck with getting the app store approval. Hopefully they will throw you a bone just like they did to Musi the music streaming app that uses youtube. It would be great to see this app on the app store
