### ISSUE TITLE
Branch `main` does not compile due to invalid dependencies

### ISSUE THREAD

**Issue by Drarok** [yattee/yattee#255]
> Dependencies could not be resolved because no versions of 'siesta' match the requirement 1.5.0..<2.0.0 and root depends on 'siesta' 1.5.0..<2.0.0.

**Comment by Drarok** [comment]
Seems you need to go to File -> Packages -> Resolve Package Versions, which isn't mentioned in the [building instructions](https://github.com/yattee/yattee/wiki/Building-instructions) currently.

**Comment by arekf** [comment]
I updated packages and just tried on a fresh VM and it builds. Let me know in case this is still an issue.
