### ISSUE TITLE
Saved Playlists

### ISSUE THREAD

**Issue by jacklroberts** [yattee/yattee#259]
I’m having issues with playlists with Invidious, the playlists I’ve saved on the website don’t seem to be syncing over to the app. Playlists I’ve created are syncing just fine, but with saved playlists the playlist is syncing but the videos inside aren’t

**Comment by arekf** [comment]
I need to add special handling for saved playlists which work slightly different in the API than the custom created ones, should be feasible to do soon.

**Comment by jacklroberts** [comment]
Ok, thank you very much for your response.

Take care and have a great day. 👍

**Comment by arekf** [comment]
Support for saved playlist is added in build 85

**Comment by jacklroberts** [comment]
Thank you very very much, I really do appreciate it.

Have a lovely day !!!!
