### ISSUE TITLE
after closing a video, top buttons move up on status bar

### ISSUE THREAD

**Issue by debpalash** [yattee/yattee#263]
top nav buttons go up middle status bar few pixels

**Comment by debpalash** [comment]
btw this happens on each tabviews

**Comment by arekf** [comment]
I don't understand where this glitch is. Please attach screen recording and system version.

**Comment by debpalash** [comment]
@arekf please notice searchbox and nav buttons on ios 15.5


https://user-images.githubusercontent.com/4178343/185611687-200dfbe9-3f16-4fa5-b244-84443adfd11a.MOV

**Comment by stonerl** [comment]
@debpalash This should be fixed. Can you confirm this?

**Comment by debpalash** [comment]
> @debpalash This should be fixed. Can you confirm this?

moved to android hehe
