### ISSUE TITLE
not playing area being sticky required?

### ISSUE THREAD

**Issue by debpalash** [yattee/yattee#266]
mostly it being empty sticky is not required, only requires if user played something and continues in bg and user now doing something else

**Comment by arekf** [comment]
Sorry but I don't get this one again. What do you mean by "sticky"?

**Comment by debpalash** [comment]
i mean this area exists even if nothing is playing.

![F22EC7CF-3C19-4E0A-8ACE-04EF45433A98](https://user-images.githubusercontent.com/4178343/185609435-af6f1ffd-55bf-4373-93b5-64c83b240d85.jpeg)

**Comment by arekf** [comment]
This has been resolved in previous releases (bar is not visible when not playing)
