### ISSUE TITLE
channel view window stutters

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#271]
This issue can be seen every time when the channel is opened, as the channel window pops up from bottom, it stutters.

I don't remember this issue in build 80, but present in build 81. also it mayn't clearly visible in this below clip but visible for me in-person.

_ps. as I already mentioned this in Matrix, I this open issue as a placeholder._

#### Clip

https://user-images.githubusercontent.com/96393348/185715019-7d99bf22-0bb4-426a-ac84-7865bc811312.mp4

**Comment by arekf** [comment]
I am closing this one since channel navigation has changed and no longer uses popup window
