### ISSUE TITLE
player overlay settings -> Quality Profile issue

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#272]
As you can see in the image below, the quality profile is set for `720p AV - HLS, Stream` but the quality profile is showing it as `Auto`. **actually the content is played in `720p stream`**.

#### Issues that needs to solved:
1. _the text is not consistent, it needs to `Auto` or `Automatic` in the overview of the settings and also inside the dropdown box._

2. _in this case of `720p AV - HLS, Stream`, the Quality Profile should show as `720p AV - HLS, Stream` instead of `Auto`._

3. _also as an additional info the in the stream box, it shows as `720p` but it should also need to display format of video like `Stream, HLS, etc.`_ 

#### Screenshot
![image](https://user-images.githubusercontent.com/96393348/185716088-94128078-9654-4072-931c-5b7a35b2a75c.png)

**Comment by arekf** [comment]
Fixed in build 85
