### ISSUE TITLE
Settings > Quality Profile: user defined Resolution is not persistent {build81}

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#273]
there is a problem with resolution in quality profile; **as you see when I create a profile with 360p resolution `{360p AV - HLS, Stream}`, it automatically reverts back to 720p `{720p AV - HLS, Stream}`**.

I don’t remember this exist in build 80, but this issue is persistent for me in build 81.

_**Also, as you can see in the clip when opening saved profile, for a split-second it shows `1080p 60fps` and goes back to the actual defined resolution. I think there is an issue with the quality profile which needs to handled.**_

#### Clip

[qualityprofileres.zip](https://github.com/yattee/yattee/files/9385715/qualityprofileres.zip)

_ps. the video clip is 12.3 MB, couldn't upload without zipping it._

**Comment by arekf** [comment]
Fixed in build 85
