### ISSUE TITLE
Stream directly from YouTube

### ISSUE THREAD

**Issue by ph00lt0** [yattee/yattee#277]
Given the following:
1.  Piped's infrastructure isn't always as reliable .
2. Google knows anyway what video's are streamed.
3. If you use a VPN it doesn't really matter whether you stream through a proxy.
4. Using piped shifts trust to that project when it comes to privacy

I would like to see an option to stream directly from YouTube through the app, much like NewPipe does.

**Comment by arekf** [comment]
Duplicate of #165
