### ISSUE TITLE
Invidious seems to crash app

### ISSUE THREAD

**Issue by Jenni32222** [yattee/yattee#28]
Using beta 4 release on an iPhone XS Max running iOS 15.1. Using the app using Piped will simply work and play videos, however when adding an Invidious instance, thumbnails and videos will not work. When trying to play a video, the app will freeze and crash after a couple of seconds.

**Comment by arekf** [comment]
I am using the app with my private Invidious instance with no issues.
Are you using recent Invidious version?

I created a build that displays logs in the bottom of the Settings, please install it and copy logs with errors with loading thumbnails, maybe it will give some clue.

Download:
[Yattee.ipa.zip](https://github.com/yattee/yattee/files/7654931/Yattee.ipa.zip)

**Comment by Jenni32222** [comment]
Thanks for the build.
I am indeed using the latest Invidious build, API seems to be doing fine with other applications.
Here are the logs:

`Siesta:network        │ Cache request for Resource(https://invidious.r0b1nz.nl/api/v1/videos/NvKjO-8DusE)[]
Siesta:network        │ GET https://invidious.r0b1nz.nl/api/v1/videos/NvKjO-8DusE
Siesta:network        │ Cache request for Resource(https://invidious.r0b1nz.nl/api/v1/search?q=Apple%20Pie%20Recipes&sort_by=upload_date&type=all)[]
Siesta:network        │ GET https://invidious.r0b1nz.nl/api/v1/search?q=Apple%20Pie%20Recipes&sort_by=upload_date&type=all
Siesta:network        │ Cache request for Resource(https://invidious.r0b1nz.nl/api/v1/channels/UC-lHJZR3Gqxm24_Vd_AJ5Yw/latest)[]
Siesta:network        │ GET https://invidious.r0b1nz.nl/api/v1/channels/UC-lHJZR3Gqxm24_Vd_AJ5Yw/latest
Siesta:network        │ Cache request for Resource(https://invidious.r0b1nz.nl/api/v1/trending?region=US&type=Trending)[]
Siesta:network        │ GET https://invidious.r0b1nz.nl/api/v1/trending?region=US&type=Trending
Siesta:network        │ GET https://invidious.r0b1nz.nl/api/v1/search?q=Apple%20Pie%20Recipes&sort_by=upload_date&type=all
Siesta:network        │ GET https://invidious.r0b1nz.nl/api/v1/channels/UC-lHJZR3Gqxm24_Vd_AJ5Yw/latest
Siesta:network        │ GET https://invidious.r0b1nz.nl/api/v1/trending?region=US&type=Trending
Siesta:network        │ Response:  200 ← GET https://invidious.r0b1nz.nl/api/v1/videos/NvKjO-8DusE
Siesta:stateChanges   │ Resource(https://invidious.r0b1nz.nl/api/v1/videos/NvKjO-8DusE)[] received new data from network : Entity<Any>(content: Yattee.Video(id: "NvKjO-8DusE", videoID: "NvKjO-8DusE", title: "NBA Youngboy - Heart & Soul / Alligator Walk", thumbnails: [Yattee.Thumbnail(url: https://invidious.r0b1nz.nl:3000/vi/NvKjO-8DusE/maxres.jpg, quality: Yattee.Thumbnail.Quality.maxres), Yattee.Thumbnail(url: https://…
Siesta:network        │ Response:  200 ← GET https://invidious.r0b1nz.nl/api/v1/channels/UC-lHJZR3Gqxm24_Vd_AJ5Yw/latest
Siesta:stateChanges   │ Resource(https://invidious.r0b1nz.nl/api/v1/channels/UC-lHJZR3Gqxm24_Vd_AJ5Yw/latest)[L] received new data from network : Entity<Any>(content: [Yattee.Video(id: "Ss_CbwsMBRQ", videoID: "Ss_CbwsMBRQ", title: "He\'s 12? ZAMN!", thumbnails: [Yattee.Thumbnail(url: https://invidious.r0b1nz.nl:3000/vi/Ss_CbwsMBRQ/maxres.jpg, quality: Yattee.Thumbnail.Quality.maxres), Yattee.Thumbnail(url: https://invidious.r0b1nz.nl:3000/vi/…
Siesta:network        │ Response:  200 ← GET https://invidious.r0b1nz.nl/api/v1/channels/UC-lHJZR3Gqxm24_Vd_AJ5Yw/latest
Siesta:stateChanges   │ Resource(https://invidious.r0b1nz.nl/api/v1/channels/UC-lHJZR3Gqxm24_Vd_AJ5Yw/latest)[D] received new data from network : Entity<Any>(content: [Yattee.Video(id: "Ss_CbwsMBRQ", videoID: "Ss_CbwsMBRQ", title: "He\'s 12? ZAMN!", thumbnails: [Yattee.Thumbnail(url: https://invidious.r0b1nz.nl:3000/vi/Ss_CbwsMBRQ/maxres.jpg, quality: Yattee.Thumbnail.Quality.maxres), Yattee.Thumbnail(url: https://invidious.r0b1nz.nl:3000/vi/…
Siesta:network        │ Response:  200 ← GET https://invidious.r0b1nz.nl/api/v1/trending?region=US&type=Trending
Siesta:network        │ Response:  200 ← GET https://invidious.r0b1nz.nl/api/v1/search?q=Apple%20Pie%20Recipes&sort_by=upload_date&type=all
Siesta:stateChanges   │ Resource(https://invidious.r0b1nz.nl/api/v1/search?q=Apple%20Pie%20Recipes&sort_by=upload_date&type=all)[L] received new data from network : Entity<Any>(content: [Yattee.ContentItem(video: Optional(Yattee.Video(id: "-Z6hVJHN0fk", videoID: "-Z6hVJHN0fk", title: "Fried Apple Pie Pockets | Apple Pie Recipe | Homemade Apple Pie Pockets | Recipes by Saba Rizwan", thumbnails: [Yattee.Thumbnail(url: https://invidious.r0b1nz.nl:3000/vi/-Z6hVJHN0…
Siesta:stateChanges   │ Resource(https://invidious.r0b1nz.nl/api/v1/trending?region=US&type=Trending)[L] received new data from network : Entity<Any>(content: [Yattee.Video(id: "NvKjO-8DusE", videoID: "NvKjO-8DusE", title: "NBA Youngboy - Heart & Soul / Alligator Walk", thumbnails: [Yattee.Thum`

**Comment by FireMasterK** [comment]
> https://invidious.r0b1nz.nl:3000/

That instance appears to be misconfigured, although that may not be the problem here.

**Comment by arekf** [comment]
> > https://invidious.r0b1nz.nl:3000/
> 
> That instance appears to be misconfigured, although that may not be the problem here.

That's correct, instance's API returns URLs including the 3000 port which makes them invalid (example: https://invidious.r0b1nz.nl/api/v1/popular) . I don't know why the Invidious front end still works for this instance (maybe the port is stripped client-side), but it doesn't seems as something that I want to be handling in Yattee.

I am closing this for now, if this gets resolved on the instance side and there are still other issues, please let me know, I will be able to debug as the instance is publicly avaible.

**Comment by Jenni32222** [comment]
Thanks, Invidious is running behind Nginx. May that be the cause of why that port is not reachable?

**Comment by arekf** [comment]
> Thanks, Invidious is running behind Nginx. May that be the cause of why that port is not reachable?

I think the instance's config should be changed to the following:
`external_port: 443`

More info here: https://docs.invidious.io/Configuration.md

Let me know if that helped.

**Comment by Jenni32222** [comment]
That seemed to have done the trick, thanks a lot! Keep up the great work on the app 👍

**Comment by arekf** [comment]
And thanks to you for reporting, I was able to address the crash that happened when you tried to play videos (reason was the video thumbnail that could not be loaded)
