### ISSUE TITLE
add `edit` option to custom locations

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#284]
add the `edit` option to the `custom locations`, at the moment `Remove` option is only one available and I can't able to re-write the existing location.

possibility of editing, changing the URL of the existing location using this requested option.

#### Screenshot

![IMG_0184](https://user-images.githubusercontent.com/96393348/187247172-1ce61f8a-97cb-495f-9f24-d85d96094dd3.jpeg)

**Comment by stonerl** [comment]
This is implemented. Closing this one.
