### ISSUE TITLE
[Feature request] Save/Download videos for offline viewing

### ISSUE THREAD

**Issue by F3000** [yattee/yattee#286]
Hi , 

I have just discovered this app today and I'm wondering if it is possible to watch videos offline etc...

Back in iOS 6 days I had an app what had this feature . 

Maybe you can use YouTube-DL or something similar for that 
https://youtube-dl.org/

That would be useful when traveling via Airplane with no internet etc... (or with German railway 🤣)

**Comment by arekf** [comment]
Duplicate of #17
