### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [yattee/yattee#287]
So https://github.com/yattee/yattee/blob/main/LICENSE is AGPLv3
whereas
https://hosted.weblate.org/projects/yattee/localizations/#information
went from GPLv2+ to LGPLv3+ (not possible)
The glossary is still GPLv2+, so it seems setting both to AGPLv3+ in
https://hosted.weblate.org/settings/yattee/localizations/
and
https://hosted.weblate.org/settings/yattee/glossary/
was the intended fix.

**Comment by comradekingu** [comment]
Closing as fixed :)
https://hosted.weblate.org/projects/yattee/localizations/#information

**Comment by arekf** [comment]
Thanks and sorry for the hassle 😅
