### ISSUE TITLE
yattee unable to display video thumbnail

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#288]
This issue happens like from time to time, _**sometimes the app can’t load the video thumbnails or a thumbnail of livestream**_ but these thumbnails are visible and available via the instances in web browser.

this is same on the piped and invidious.

#### Screenshot

**_In Yattee_**
![4429A82B-EC35-427E-AFF2-72358FC58E9F](https://user-images.githubusercontent.com/96393348/188282848-febc7017-5d52-4fcf-bee6-74150754dbb9.jpeg)
![2489C2F6-0DD4-4B4D-BF1B-9A01C7F53659](https://user-images.githubusercontent.com/96393348/188282857-463a35eb-37bf-4463-afe3-a438f15eacb9.jpeg)

**_In Browser_**
![4A0E1CC3-A3B8-4214-8A33-D086EB6F0374](https://user-images.githubusercontent.com/96393348/188282884-a89ec1d7-c2bd-477d-aac4-2602634298ba.jpeg)

**Comment by F3000** [comment]
Seen this today on tvOS . After logging in with piped account I can't see thumbnails anymore

**Comment by arekf** [comment]
Resolved in build 93
