### ISSUE TITLE
Sign in with TVOS

### ISSUE THREAD

**Issue by uratrtl** [yattee/yattee#29]
I side loaded the latest version from the github to my apple TV4k. I am not seeing a way to log in to my account on youtube.

**Comment by Jenni32222** [comment]
What do you mean you can't sign in with a YouTube account? This is an app for Piped and Invidious

**Comment by arekf** [comment]
You cannot login with YouTube.
Added more information to Wiki: 
[How to login to my account?](https://github.com/yattee/yattee/wiki/How-to-login-to-my-account%3F)

**Comment by uratrtl** [comment]
> You cannot login with YouTube. Added more information to Wiki: [How to login to my account?](https://github.com/yattee/yattee/wiki/How-to-login-to-my-account%3F)

thanks, didn't realize, this probably should have been asked on a discord or something.
