### ISSUE TITLE
[Bug] Missing account button

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#293]
iPhone SE 2016 iOS 15.6.1

Trying to login to Piped but seem to be missing the account button as seen here:

![playlists](https://user-images.githubusercontent.com/47334163/188499200-85f500a7-9599-4d3e-82ab-6a14a1e269e7.png)

-- 

![IMG_C80FC96AD38E-1](https://user-images.githubusercontent.com/47334163/188499213-d430bddf-4a3b-4498-894f-815673fa384e.jpeg)

**Comment by arekf** [comment]
Did you add custom instance in Location settings? You cannot use public instance for logging in

**Comment by bbsixzz** [comment]
No, are you saying I need to host my own instance in order to use this function?

I registered on https://piped.kavin.rocks and thought I could just add that account as seen on the Apple TV:


![](https://r.yattee.stream/screenshots/tvOS/settings.png)
