### ISSUE TITLE
implement `Back` button

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#298]
This issue is to request the implementation of the `Back` button as shown in the image below, as the yattee doesn't have this option.

**Currently in yattee, it is very difficult go for the previous page in a way that one should want or every other tool/app works. the current only option cancel or exit button doesn't work in most case as want in this context.
For example, in this image (as you know) you can see that the `Back` button only appears at the place where the previous page or history of page is formed.**

I would like to see this kind of implementation is possible, also I have seen in few other apps, which works same way as this one relies on the swift function.

#### Screenshot (from Apple Music as example)
![IMG_6620](https://user-images.githubusercontent.com/96393348/189473232-0e3e413f-1d16-4195-a551-e6109c98132d.jpeg)

**Comment by arekf** [comment]
I am closing this as new navigation includes this
