### ISSUE TITLE
Mac & tvOS: Unable to see videos older than 19 hours

### ISSUE THREAD

**Issue by Traace** [yattee/yattee#301]
Hi,

videos older than 19 hours don't appear in my subscription tab in yattee. In Invidious Web there is a "Next Page" button under the last video, in yattee the button is missing.

Tested with MacOS 12.6 (M1 Chip), tvOS 16 and Invidious

**Comment by Traace** [comment]
On tvOS its the same, so it doesn't only affect MacOS. I changed the title and edited the description.

**Comment by suymur** [comment]
> EDIT: If you go to your account settings in Invidious there is an option called "Number of videos to show in feed" I set this to 1000 and the issue is resolved.

This solved it for me, thank you!

**Comment by Traace** [comment]
Solved. Setting it in Invidious works fine for me.
