### ISSUE TITLE
Videos not charging

### ISSUE THREAD

**Issue by pussina** [yattee/yattee#302]
This week I installed Yattee on my Ipad pro 9.7 with ios 15.6.1, and I was enjoying the app, but suddenly, today, non of the videos nor the searches were charging. I can't even see the title or the cover of the video. I'm pretty new to this so I may have screwed up during the process.

P.d: my method of installation was through AltStore.

**Comment by arekf** [comment]
There are ongoing issues with Piped official instance. I've removed it from instances list, it should work again. If you encounter issues like that in the future, you can go to Settings > Locations and tap "Switch to other public location".

**Comment by pussina** [comment]
Thanks man, I'm delighted that there exist people that spend their time helping the rest ^^.
