### ISSUE TITLE
Progress bar doesn't show runtime

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#303]
If you see the image below, the time on the progress bar is at 00:00 and it doesn't work as it should be.
It always stays at 00:00 and this bug resolves when I try tapping on the progress bar and scrubbing the time.

_ps. I have removed the screenshot as I found it didn't capture the player controls while taking the screenshot and I can't reproduce this bug again now._

**Comment by arekf** [comment]
I can't find how to break it, If you happen to find reproduction steps then let me know so I can reopen.
