### ISSUE TITLE
[Bug] could not open channel when clicking direct video link

### ISSUE THREAD

**Issue by F3000** [yattee/yattee#320]
When I click following link I get the error in the picture:

https://www.youtube.com/watch?v=N9WHp8DG2WY

![image](https://user-images.githubusercontent.com/8161283/193155091-92493db1-9f5e-4c47-8401-b53998894e5a.jpeg)

**Comment by arekf** [comment]
Can you check with latest build and if it still does not work provide more info on the instance used? I tested with both Invidious and Piped and it worked fine for me.
