### ISSUE TITLE
Manifest URL doesn't populate content

### ISSUE THREAD

**Issue by Iliski** [yattee/yattee#332]
IPhone 14 Pro
IOS 16.0.2
Yattee 1.4 (Build 99)

Steps to reproduce:
Input manifest URL in advanced under settings ( https://r.yattee.stream/manifest-invidious-piped.json )

Trending/Popular do not update, search function is also broken. Videos do load and play though.

**Comment by t3dium** [comment]
Yeah, I also had this issue at first but found a 2nd setting u also have to change. 

Go to locations under settings, pick a country, and then press the switch to other locations button to select ur instance.

Alternatively, add a custom location from either this list (piped, has a bit more features) : <https://github.com/TeamPiped/Piped/wiki/Instances> or this list (invidious): <https://api.invidious.io/>. Which has a lot more sources.

**Comment by Iliski** [comment]
Thank you so much! That fixed it instantly.
