### ISSUE TITLE
Recent Youtube and Piped update made lots of video inaccessible. 

### ISSUE THREAD

**Issue by upstroke-version** [yattee/yattee#336]
Recently youtube and piped updated the UI to have tabs on channel page. this is how it looks like on Piped for example. 

![1](https://user-images.githubusercontent.com/96179742/199928744-0e58c407-f86f-4fef-8821-2acaaa82ec3c.png)

The notable change is that the main ”videos” tab does not show livestream archives and shorts anymore, and these videos are moved to their own tabs. Which is kinda huge problem because some youtubers mainly focus on livestreams and those livestream archives are a huge part of their video feed, and now those videos are basically inaccessible through Yattee since it only shows "videos" tab.

**Comment by acidghost** [comment]
@arekf, the fix for this on Invidious side has recently landed iv-org/invidious#3371.

**Comment by arekf** [comment]
This has been resolved in previous builds (channel pagination and content type pages for shorts, playlists etc)
