### ISSUE TITLE
Video takes much longer to stream and is often low quality as compared to Piped, Invidious and YouTube on the web.

### ISSUE THREAD

**Issue by chadify** [yattee/yattee#35]
My average internet speed is around 5 Mbps.

**Comment by arulagrawal** [comment]
Seeing the same on a ~200Mbps network, where the adaptive (HLS) stream from a piped instance is often really low quality and switching to 1080p takes a really long time.

**Comment by martin-nohava** [comment]
+1 (on macOS)
Also seeing very low quality on HLS option. Switching manually to 1080p or 720p option takes a long time for me as well (somewhere about 10 to 20 seconds), but after that Yattee plays entire video in respective quality without a hiccup.

> Yattee: Version 1.3.1 (18)
> macOS: 12.1

**Comment by stripedgoat** [comment]
I can confirm this is still an existing issue on the iOS app. Also, if I switch manually to 1080p, the video often freezes and the audio keeps playing.

**Comment by martin-nohava** [comment]
> +1 (on macOS) Also seeing very low quality on HLS option. Switching manually to 1080p or 720p option takes a long time for me as well (somewhere about 10 to 20 seconds), but after that Yattee plays entire video in respective quality without a hiccup.
> 
> > Yattee: Version 1.3.1 (18)
> > macOS: 12.1

On Yattee: Version 1.4.alpha.3 (32) (MPV player) **this issue is fixed for me**. Videos starts streaming in high quality almost instantaneously, switching speed between available stream option is very improved as well.
Keep the great work, thanks. 🚀

**Comment by bachig26** [comment]
@arekf i feel like this has to do with the data loading and possibly also with the sponsorblock data read. every time the video only plays after the video description and stuff like comments, related and queue loaded. 
**I think there needs to an priority defined like video to load first and then the description and others, vice versa.**

**Comment by arekf** [comment]
> @arekf i feel like this has to do with the data loading and possibly also with the sponsorblock data read. every time the video only plays after the video description and stuff like comments, related and queue loaded.
> 
> **I think there needs to an priority defined like video to load first and then the description and others, vice versa.**
> 
> _ps.also, possibly a on/off toggle to sponsorblock._

Video links is part of video details, so it cannot start playing before details are available. Comments and other tabs are loaded on demand, when you open the tab. SponsorBlock segments are loaded asynchronously.

**Comment by arekf** [comment]
I am closing this as solved with new player in v1.4
