### ISSUE TITLE
Way to mark a video as favorite & stop rotation

### ISSUE THREAD

**Issue by peridome** [yattee/yattee#353]
Maybe I'm missing something obvious but I can't find a way to mark a video as favorite, just a channel or a search. What am I missing? Also, is there a way to prevent video from entering fullscreen mode and rotating? This is on iOS and even with the phone's rotation option locked, videos always enter fullscreen and rotate left and right. My use case is: never enter fullscreen (unless specifically asked). Thanks!

**Comment by arekf** [comment]
> Maybe I'm missing something obvious but I can't find a way to mark a video as favorite, just a channel or a search. What am I missing? 

There's no way to favorite videos, we have issue #89 with this suggestion

> Also, is there a way to prevent video from entering fullscreen mode and rotating? This is on iOS and even with the phone's rotation option locked, videos always enter fullscreen and rotate left and right. My use case is: never enter fullscreen (unless specifically asked). Thanks!

There's in app rotation lock:
![IMG_0590FD0C6571-1 2](https://user-images.githubusercontent.com/367484/205468064-e6153738-061c-45ec-9378-9788496bea47.jpeg)

However it is not working with some devices as far as I know. If you have issues you can open another issue.
