### ISSUE TITLE
No Thumbnails using Invidious

### ISSUE THREAD

**Issue by meichthys** [yattee/yattee#354]
![image](https://user-images.githubusercontent.com/10717998/203780287-d4e6d4f4-92cf-4069-8ee7-0e9808948171.png)

**Comment by Fannangir** [comment]
Same issue here.
Could the reason be HTTPS?

**Comment by arekf** [comment]
Invidious HTTPS Instance needs to be configured with this settings:
```
external_port: 443
domain: whatever.it.is
```

Without it, the Invidious frontend will show thumbnails fine but will produce wrong links in the external API used by Yattee.

**Comment by Fannangir** [comment]
I have a docker container with invidious running on Synology.
HTTPS is achieved by Nginx proxy manager.
Could you please provide additional information on what should be modified?
Should I modify the docker container?

**Comment by arekf** [comment]
In your browser, go to:
https://your.instance/api/v1/videos/ldX-ab758l8
look at URLs for "videoThumbnails". They should be exactly like:
https://your.instance/vi/ldX-ab758l8/maxres.jpg
If it returns here http or has incorrect port in url then it is badly configured and you need to set the values as I mentioned.
Links for more info for you:
https://docs.invidious.io/configuration/
https://github.com/iv-org/invidious/blob/master/config/config.example.yml
https://docs.invidious.io/installation/#docker-compose-method-production

**Comment by meichthys** [comment]
I have the same config as @Fannangir and have the following video thumbnail urls:
'''
"videoThumbnails":[{"quality":"maxres","url":"/vi/KCioI0tosUo/maxres.jpg","width":1280,"height":720},{"quality":"maxresdefault","url":"/vi/KCioI0tosUo/maxresdefault.jpg","width":1280,"height":720},
'''

I don't see anywhere to set the full url. I guess I would expect an 'instance_url' parameter in docker compose or something similar.

**Comment by Fannangir** [comment]
@arekf thank you very much.
Updated the container, you were right, it was the missing piece in the puzzle.

**Comment by FrankelJb** [comment]
@meichthys if you are using a reverse proxy and you're using https for the api then you need something like this in your docker config:
```
    environment:
      INVIDIOUS_CONFIG: |
        external_port: 443
        domain: whatever.it.is
        https_only: true
```

**Comment by BulldozerPete** [comment]
I still don't get what to do.

I have added 
 environment:
      INVIDIOUS_CONFIG: |
        external_port: 443
        domain: whatever.it.is

But still no thumbnails. Do need to change my server in Yattee from http://192.168.178.3:3000 to http://192.168.178.3:443?

**Comment by flackend** [comment]
You do not need to use HTTPS to get thumbnails working 🎉 I had this issue. I took the advice from [this comment](https://github.com/yattee/yattee/issues/354#issuecomment-1327460172) to view the API output. I didn't have the `domain` or `external_port` set. Mine are now set:

```
external_port: 3000
domain: 192.168.1.10
```

Since I'm only accessing over my VPN, this works perfect and no HTTPS required.

**Comment by MarvAmBass** [comment]
thx!
also you can use `domain: hostname` if you don't want to specify a static ip and the config - it works if your client's can resolve it
