### ISSUE TITLE
Thank you (and perhaps duplicated entried in the manifest)

### ISSUE THREAD

**Issue by lfom** [yattee/yattee#355]
Firstly, thank you a lot for providing a Piped/Invidious front end in the AppStore! I wish you all the best with the project!

I was checking the entries in the [manyfest JSON](https://r.yattee.stream/manifest-invidious-piped.json), and I saw many duplicated entries with this URL:

https://invidious-eu01.yattee.stream/

Is it a CDN so it automatically uses the best server? Or maybe the URL should be different for each country?

Thanks again! Regards.

**Comment by arekf** [comment]
The manifest is still hosted on Yattee domain but I am phasing out endorsing any public servers. I used this instance when other instance went down and I had no way to replace it with other from the same country. It has no CDN, is located in Netherlands.

You should use this manifest/instance at your own risk (just like any time using this app at all, according to the license 😜)
