### ISSUE TITLE
Don't rotate to portrait when upside down

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#358]
I'd love an option to make the IOS player not rotate back to portrait mode when turned upside down while watching a video. The current behavior makes it hard to watch videos while lying down since the player flips back to portrait when you rotate your phone to match your eyes.

**Comment by arekf** [comment]
Maybe I am misunderstanding or there is a bug but can't you use rotation lock in the app?
![IMG_0590FD0C6571-1 2](https://user-images.githubusercontent.com/367484/205468186-f5038e9e-7520-4054-a43c-02ef6ffae5cc.jpeg)

**Comment by Insprill** [comment]
Oh, I never saw that button - thank you! I still think this issue is valid however as the screen would still be upside down relative to your phone, and you'd have to unlock and relock it to change the direction your phone is oriented.
