### ISSUE TITLE
Rotating to landscape returns you to the search page

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#359]
After opening a video ~~from the subscriptions tab~~, once the player is turned into landscape mode and back, you will be returned to the top of the search page. Tested on an iPhone 8+ running IOS 16.1.1 with yattee 1.4.2 build 112

https://user-images.githubusercontent.com/52843537/205174157-d37ab328-0339-4900-b602-e99945a28b15.mov

**Comment by Diaub** [comment]
I'm experiencing the same bug with iPhone 12 / iOS 16.1.1 (Yattee 1.4.2 build 112).

**Comment by Insprill** [comment]
Appears to be fixed with 1.4.3 build 142.
