### ISSUE TITLE
Unable to delete videos from invidious playlists and as well as the playlist itself.

### ISSUE THREAD

**Issue by chadify** [yattee/yattee#36]

**Comment by chadify** [comment]
This is a bug. I’m unable to delete using above mention steps.

**Comment by chadify** [comment]
Uploading IMG_8097.MP4…

**Comment by chadify** [comment]
https://user-images.githubusercontent.com/72332949/146117448-241d9985-64ed-4837-84c4-e316c6d270b5.MP4

**Comment by arekf** [comment]
@chadify I've improved handling of playlists to show errors.

Please install [latest release](https://github.com/yattee/yattee/releases/tag/v1.3-beta.1) and update what error are you getting.

**Comment by chadify** [comment]
I’ve installed the latest beta build. Here’s the screenshot.
![D6C3F0F8-FB45-4D4F-B9E4-4345D617A71A](https://user-images.githubusercontent.com/72332949/146631376-6a9f2210-0b50-444e-a1b1-53d39cc49ac9.png)

**Comment by chadify** [comment]
https://user-images.githubusercontent.com/72332949/146639942-2e241301-2ac3-40a5-8e98-28f54eb6ef73.MOV

**Comment by arekf** [comment]
I am assuming you are using self-hosted Invidious instance - can you check your instance log to see if there are any queries made when removing playlist?

**Comment by chadify** [comment]
Ok, the instance I was using was vid.puffyan.us and I find out the there was no option to delete the playlists and the videos, in it, on the website itself. So, it isn't a bug of the app.

 Do have knowledge of other invidious instance which support/can be added into this app?

**Comment by chadify** [comment]
How do I check instance log?

**Comment by arekf** [comment]
> How do I check instance log?

I meant Invidious webserver logs, you can't see it unless you're instance owner.

I investigated this further an it's unlikely it's a bug but rather unusual configuration/modification to Invidious instance which prevents from making API calls to these playlist endpoints.

For example: [vid.puffyan.us](https://vid.puffyan.us) has this problem while everything's fine with [vid.mint.lgbt](https://vid.mint.lgbt).
