### ISSUE TITLE
Adjust fast-forward/reverse button intervals

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#368]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Usability improvement

### Describe the feature

An option to adjust by how many seconds the video is forwarded/reversed when double tapping (on IOS) or clicking the seek buttons. I prefer to set it set at 5 seconds, while other people prefer to have it longer than 10 seconds. An option with maybe a slider between 2 and 60 seconds would be nice to adjust it exactly as preferred, or just a dropdown with some common intervals between 5 and 60 seconds.

**Comment by arekf** [comment]
This has been implemented in TestFlight builds
