### ISSUE TITLE
Make the video playing in PiP mode automatically switch to normal video player when the app is reopened.

### ISSUE THREAD

**Issue by chadify** [yattee/yattee#37]
Currently the PiP mode remains on when reopening the app.

**Comment by arekf** [comment]
To put video back to in-app player you should use this PiP button:

![73064B12-2B03-41DA-8B44-6C92F6DA7447_1_201_a](https://user-images.githubusercontent.com/367484/146083408-35695635-5c3d-4691-92fe-537b9f4fe5db.jpeg)

I don't see why opening the app would switch from PiP to regular player. You might want to just browse list of videos what to watch next. TV app is doing the same (keeping PiP).

It could be added as an interface customization option if you could elaborate better why is that important. Thank you.

**Comment by chadify** [comment]
This is a feature in the YouTube app and it felt more seamless and intuitive. I only use PiP when browsing stuff outside of the app, when in the app there’s already a mini player so I never feel any need for PiP in the app. 

I think it’s more convenient for PiP to disappear when in the app. You may add it as an toggle in the settings if it’s not much bother in writing the code for it.

**Comment by chadify** [comment]
I guess the best senario will be when on/scrolling the feed(ie. popular, favourites, playlist pages) the PiP remains active
![1F37D206-A1A1-46A1-897C-4506CB33F8D5](https://user-images.githubusercontent.com/72332949/146646197-8153dd14-3e1d-4e81-b10e-7573025329ff.jpeg)


 but when opening the player it switches back to normal mode.

![BB2EE20D-60F8-4654-BC4A-A7BCC21A1364](https://user-images.githubusercontent.com/72332949/146646249-157503ef-5ebb-40da-b6f3-6fca55cc23cc.jpeg)

**Comment by arekf** [comment]
@chadify 
I've added 3 new options to configure PiP behavior, let me know if you have more thoughts on this.

**Comment by chadify** [comment]
The new update is well welcomed. But there’s one issue(when the option “close PiP when player is opened” is selected): PiP only closes when the player is reopened, it stays if I’m already on the player.

For example:

https://user-images.githubusercontent.com/72332949/146711138-91f86882-31dc-4db3-a73a-a3c345768543.MOV

When re switching to Yattee, if it is already on the player page, the PiP does not closes itself. I’d like to have the otherwise. 

Also, it’d be great if you make the PiP closing animations more fluid and smooth(for example, see the YouTube app PiP animations).

**Comment by chadify** [comment]
@arekf One more helpful option would be to automatically switch to PiP mode when closing the player while the app still being in the foreground.
