### ISSUE TITLE
Changing quality resets video position

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#371]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Changing a video's quality will reset you back to the beginning, or its last saved location.

### Expected Behavior

When you change the video quality, it should resume from where it was before the change.

### Device & OS Version

iPhone 8+, IOS 16.1.2

### App Build

1.4.2 build 112

### Screenshots, Videos and other files

It's a little hard to see as text is in the way, but I was about 5:40 into the video, changed the quality, and went right back to the beginning.

https://user-images.githubusercontent.com/52843537/206805451-088731b4-bf29-4066-87a7-1d476c3f246f.mov

**Comment by stonerl** [comment]
@Insprill Doesn't happen with the latest build (181). Can you test this?

**Comment by Insprill** [comment]
The latest version on the app store is 174, so I can't test it until it release.

**Comment by stonerl** [comment]
If you like, you could install the latest build via TestFlight. [Instructions are here](https://github.com/yattee/yattee/wiki/Installation-instructions).

**Comment by stonerl** [comment]
Was still an issue with the latest build. I made a PR to fix the issue.
