### ISSUE TITLE
Clickable timestamps

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#376]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Usability improvement

### Describe the feature

The ability to click on timestamps in comments and video descriptions and seek to that point in the video. It's pretty common that people will write a comment with a timestamp of what they're referring to, and it's useful to just click on the timestamp they provided instead of seeking there yourself.

**Comment by stonerl** [comment]
Clicking timestamps in the description already works.

Can you provide some videos with timestamps in the comments?

**Comment by Insprill** [comment]
The WAN show from LTT always has timestamps in the comments & description
https://www.youtube.com/watch?v=J2SvnnVBDk0
