### ISSUE TITLE
[Bug] Missing thumbnails tvOS

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#378]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Thumbnails are missing on Piped instances (tried multiple), works with Invidious.

Problem appears in Home, Subscriptions Trending and Playlist.

This does not happen with build 122 on iOS using the exact same Piped instances and app settings.

Clearing the cache doesn't help.

### Expected Behavior

Thumbnails

### Device & OS Version

tvOS 16.2

### App Build

122

### Screenshots, Videos and other files

![CCF1C9D0-E72E-49FD-B66C-9A58F2AE2ADC](https://user-images.githubusercontent.com/47334163/209064504-87ad4749-3f65-4f0f-95fe-c6963294bdd0.jpeg)

**Comment by bbsixzz** [comment]
P.S.

The button alignment for cells and refresh is off on the Subscriptions page.

**Comment by arekf** [comment]
This should got resolved in build 124.

I will fix improper alignment of buttons and bring new view options to other pages before App Store release.
