### ISSUE TITLE
Piped comments now include HTML

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#379]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When using newer versions of Piped, comments show the raw HTML instead of only the content. This change was made two weeks ago in https://github.com/TeamPiped/Piped-Backend/pull/481.

### Expected Behavior

Comments should only show the content

### Device & OS Version

iPhone 8+, IOS 16.1.2

### App Build

1.4.2 build 112

**Comment by arekf** [comment]
Thanks for all the issues you've created so far. This one has been fixed in recent TestFlight build.
