### ISSUE TITLE
[Bug] scrub bar is behind app switcher bar (FaceID iPhone)

### ISSUE THREAD

**Issue by F3000** [yattee/yattee#382]
I think the picture describes it better :) 

Workaround : 
Wait 5 seconds until bottom bar hides automatically 

![image](https://user-images.githubusercontent.com/8161283/209684026-14f58161-dd6b-4311-a2bd-16386d9ae641.jpeg)

**Comment by bbsixzz** [comment]
Yeah this is problematic.

**Comment by rootedetc** [comment]
The scrub bar by itself is too small for newer iPhones as well.
This, together with the issue you have mentioned, makes it almost unusable.
