### ISSUE TITLE
Match options - control buttons and action buttons

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#384]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Usability improvement

### Describe the feature

Please match control options, settings is already available in both for example. 

I find it much easier to use the larger action buttons in general, I was looking to add Music Mode as an action button.

![0A0BC369-9894-47A5-856A-655E9C5C03B3](https://user-images.githubusercontent.com/47334163/210083103-a01831cc-bd87-4197-98e2-6ee4bb5099db.png)

**Comment by arekf** [comment]
Added in version 1.4.3
