### ISSUE TITLE
Piped VOD playback issue

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#385]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

After a live stream is finished and turns into a VOD, for a couple of hours afterward it isn't watchable. It will only play the last few seconds, and nothing earlier. This is not an issue though the Piped UI. Scrubbing back further in the video does not work. I mostly notice this with the WAN show as most people I follow don't live stream.

### Expected Behavior

The VOD would play from the beginning.

### Device & OS Version

iPhone 8+, IOS 16.1.2

### App Build

1.4.2 build 112

### Screenshots, Videos and other files

https://user-images.githubusercontent.com/52843537/210128632-a60daa6d-7f12-437f-ab85-f1687f0eb404.mov

**Comment by stonerl** [comment]
@Insprill Does this still happen with the latest build (181)?
