### ISSUE TITLE
[Feature Request] add audio only option

### ISSUE THREAD

**Issue by Smig0l** [yattee/yattee#389]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

New feature

### Describe the feature

it would be cool to add an audio only mode to default all videos.
for example piped: 
![image](https://user-images.githubusercontent.com/109904155/211356740-98fccbb6-6ee8-4f24-892c-9fd5feec7c2d.png)

**Comment by gonzoknows** [comment]
this would be nice feature for those who want to stream music

**Comment by Smig0l** [comment]
Found a temporary workaround:
When playing a video just swipe down/hide it (so the controls appears at the bottom) and then put yattee in background

**Comment by gonzoknows** [comment]
> Found a temporary workaround: When playing a video just swipe down/hide it (so the controls appears at the bottom) and then put yattee in background

I've done this before it works well

**Comment by stonerl** [comment]
Yattee has a Music Mode now, closing this one.

**Comment by Wrestor** [comment]
> Yattee has a Music Mode now, closing this one.

Can you add music Mode to yattee for Apple TV as well?
