### ISSUE TITLE
Favorites not loading - Invidious API Change

### ISSUE THREAD

**Issue by Outlet7493** [yattee/yattee#391]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Favorites on the homepage have stopped working after an Invidious API update.

https://github.com/iv-org/documentation/commit/dca939835c8a5909b450440be29006360d682eae

### Expected Behavior

Videos in the carousel no longer load but used to - they just infinitely show placeholder cards.

### Device & OS Version

iPadOS 16.2

### App Build

112 (Yattee 1.4.2 - App Store)

### App Settings

Custom Invidious instance

**Comment by gonzoknows** [comment]
Getting the same issue favorites don't load, although when searching videos they play fine

**Comment by arekf** [comment]
This should be resolved in build 136
