### ISSUE TITLE
Fullscreen Problems

### ISSUE THREAD

**Issue by patrickse** [yattee/yattee#397]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I've I rotate my iPhone 13 to landscape mode. The video goes fullscreen and immediately switches back to portrait mode. For whatever reason it wont stay in landscape mode.

### Expected Behavior

Rotate the iPhone to landscape mode. Video switches to fullscreen and stays like this until a rotate the Phone back to Portrait mode

### Device & OS Version

iPhone 13, iOS 16.2

### App Build

1.4.2 (build 112)

### Screenshots, Videos and other files

https://user-images.githubusercontent.com/2691200/214882410-4cfd2072-386b-44b8-b8be-1973ddf510a3.mp4

**Comment by stonerl** [comment]
Does not happen with the latest build (181) anymore.

@patrickse Can you test this?

**Comment by stonerl** [comment]
Close as fixed.
