### ISSUE TITLE
[Request] Keep playing video when swiping down in app, instead of pausing first.

### ISSUE THREAD

**Issue by CanIHelp101** [yattee/yattee#40]
Currently, when swiping down on a video to continue browsing Yattee, by default, the video is paused at the bottom. Making it continue playing by default, instead of pausing it by default and having to press play again, would be very convienant, or an option to choose so in settings. Doing so would mimic the native Youtube app. Also, adding the ability to swipe down again, on the mini player to close the video/remove it from the bottom would be a nice touch as well. Very excited about this app btw.

**Comment by chadify** [comment]
+1

**Comment by arekf** [comment]
@CanIHelp101 @chadify 
I've added a setting to keep playing when player is dismissed.

You can tap and hold on title on player bar to open context menu to close current video.
