### ISSUE TITLE
Troubleshooting steps? Location manifest not loading

### ISSUE THREAD

**Issue by abdale** [yattee/yattee#416]
Hi, 

Are there any troubleshooting steps if the location manifest does not load?

I'm using this URL:

`https://r.yattee.stream/manifest-invidious-piped.json`

Thanks!

**Comment by abdale** [comment]
Never-mind I caught the error. The URL when copied from your website introduces whitespaces at the beginning and end.

**Comment by arekf** [comment]
I am sorry, what "my website" did your mean?

**Comment by abdale** [comment]
Sorry I thought it the website was official. 

Here is the one I used (found the link [here](https://www.privacyguides.org/en/frontends/) originally):

https://gonzoknows.com/posts/Yattee/

When you copy from this website, it comes with whitespaces.
