### ISSUE TITLE
[Bug] The favourite stack grays out after opening its context menu.

### ISSUE THREAD

**Issue by chadify** [yattee/yattee#43]
Before:
![5425A6EC-CE97-4435-BD2C-496979C772E3](https://user-images.githubusercontent.com/72332949/146664826-fac22891-cd08-4926-b143-c0f4941163d2.png)
Opening the context menu by holding:
![1D7CCC31-D7F6-4018-BF64-74BFB42B958F](https://user-images.githubusercontent.com/72332949/146664840-08e6a5c9-9092-45df-b49a-0688b7a21daf.png)

After(it grays out):
![9F4CC1C0-9379-47B4-B65F-E3B59C51F757](https://user-images.githubusercontent.com/72332949/146664850-1030d9ad-94e3-493c-99ca-c227bfbeb06b.png)

**Comment by arekf** [comment]
This should be resolved in the latest build.
