### ISSUE TITLE
iOS - Controls are clipped in full screen

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#431]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

![IMG_9298_thumb](https://user-images.githubusercontent.com/47334163/233817892-80163a0f-82fb-4edb-8eb6-db4008ed1274.jpg)

### Expected Behavior

Not clipped.

### Device & OS Version

iPhone 12 Mini iOS 16.4.1

### App Build

140

**Comment by arekf** [comment]
Build 141 should have fixed it, let me know otherwise

**Comment by bbsixzz** [comment]
Looks good, that was fast :]
