### ISSUE TITLE
[UI Interaction Improvement] Make the player hide action more inertial.

### ISSUE THREAD

**Issue by chadify** [yattee/yattee#44]
For example like when hiding the player in Apple Music, it feels more “inertial” ie. the panel moves along with my finger. It feels more natural and fluid:

https://user-images.githubusercontent.com/72332949/146665026-61db0564-90ab-456f-b189-81ab25630c3e.MOV

In Yattee it feels like flicking, unresponsive and less intuitive:

https://user-images.githubusercontent.com/72332949/146665061-afd7c85d-21e7-4fda-b7f1-b7b0b2ac7187.MOV

**Comment by CanIHelp101** [comment]
+1

**Comment by arekf** [comment]
I am closing this as solved with new player in v1.4

**Comment by chadify** [comment]
I think the animations need more work. See the closing animation of Apple Music.

**Comment by arekf** [comment]
As I said few times in the chat, the player interactions/animations will be reworked.
