### ISSUE TITLE
iOS search tab improve usability

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#441]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Usability improvement

### Describe the feature

1. Empty search tab, tap search brings up keyboard for search query.

2. Search tab with results (after hitting return), tap search to clear results (go back to recents).

**Comment by arekf** [comment]
This was added in previous builds
