### ISSUE TITLE
Option to keep player open after video finishes

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#442]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Usability improvement

### Describe the feature

Quite often I want to read comments after I've finished watching a video. With 1.4.3, when the last video in the queue is over, the player immediately closes not giving me a chance to do so without playing the video again and pausing it, clearing my watched status.

there should be an option in the player settings to allow the user to disable this behavior, and leave the player open.

**Comment by Insprill** [comment]
This behavior also causes an issue if a SponsorBlock segment goes to the end of the video. Since the last watched time is right as the segment starts, if you try to watch the video again, it'll immediately close.

https://user-images.githubusercontent.com/52843537/236893992-5a85b61e-024d-41db-8452-9f871900ee58.MOV

**Comment by bbsixzz** [comment]
Yes please add this and similar request https://github.com/yattee/yattee/issues/387
