### ISSUE TITLE
Rotating to landscape opens the last viewed channel

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#444]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Similar to #359, after rotating a video into landscape mode, you'll be returned to the last channel you looked at.

### Expected Behavior

It should leave you at the last last of the app you were viewing.

### Device & OS Version

iPhone 8+, IOS 16.4.1a

### App Build

1.4.3 build 142

### Screenshots, Videos and other files

https://user-images.githubusercontent.com/52843537/236895512-5fae4f2a-8da9-496d-a4d5-2593de4e3816.MOV

**Comment by stonerl** [comment]
Tested this with the latest build (181) and it does not happen anymore.

@Insprill Can you test this?

**Comment by stonerl** [comment]
Closing as fixed.
