### ISSUE TITLE
Plans About Moving to appstore

### ISSUE THREAD

**Issue by Akczht** [yattee/yattee#45]
Hey Yattee Guys ,

Any plans on moving to AppStore to AppStore ?

-Akczht

**Comment by arekf** [comment]
From the [FAQ](https://github.com/yattee/yattee/wiki):

>     Can I download this from the App Store/are there plans to release in the App Store?
> 
> No. Apple doesn't let third party streaming clients into the App Store.

**Comment by Akczht** [comment]
This Might help https://developer.apple.com/support/unlisted-app-distribution/

**Comment by maboroshin** [comment]
It is currently listed in the App Store on iOS. The listing on the Mac App Store is also being worked on.

[yattee FAQ](https://github.com/yattee/yattee/wiki/FAQ)

> I keep resubmitting macOS versions with every update so maybe we will get lucky one day.
