### ISSUE TITLE
tvOS thumbnail progress bar incorrect after finishing video

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#451]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Sometimes the progress bar shows incorrect information after finishing a video.

![IMG_6965](https://github.com/yattee/yattee/assets/47334163/a45df5e8-4966-454a-859e-a15b3e37707b)

### Expected Behavior

Show progress correctly.

### Device & OS Version

tvOS 16.5

### App Build

145

### App Settings

Invidious backend latest version as of this posting.

**Comment by bbsixzz** [comment]
Example video initially has no duration info, afterwards it shows 7 seconds (correct) out of 10:36 (incorrect).

Related to https://github.com/yattee/yattee/issues/449

https://github.com/yattee/yattee/assets/47334163/52d82fae-ff41-4e08-96db-5fd646416e61

**Comment by stonerl** [comment]
Should be fixed.
