### ISSUE TITLE
Open in Yattee Share Sheet Shortcut

### ISSUE THREAD

**Issue by sirnacnud** [yattee/yattee#48]
I created a shortcut that will take a youtube URL and open it in Yattee. The shortcut then shows up in the Share Sheet.

The shortcut is available at https://www.icloud.com/shortcuts/ee2d8fc87f5f4d78804b582cd778d851 if anyone wants to try it out or improve it.

Sorry if opening an issue isn't the right place to share this, but it could be useful to other users. It could also be part of the Wiki.

**Comment by arekf** [comment]
Hi @sirnacnud,
thanks for preparing the shortcut. I've added it to the [Integrations wiki page](https://github.com/yattee/yattee/wiki/Integrations).
