### ISSUE TITLE
Hard crash - Play Music

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#480]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

https://github.com/yattee/yattee/assets/47334163/f9d0e0f8-8851-47c5-b214-7e8f23ea3d3b

### Expected Behavior

To not crash.

### Device & OS Version

iOS 16.5

### App Build

151

**Comment by arekf** [comment]
Can you check with latest build if you still have this issue? If yes, please provide crash log as I can't reproduce myself.

**Comment by bbsixzz** [comment]
No longer crashing in build 155.

However if using MPV the feature doesn't work (doesn't play anything). 

Only AVPlayer works.

**Comment by stonerl** [comment]
With the latest build (181) it also works for MPV. @bbsixzz can you test this?

**Comment by bbsixzz** [comment]
Works fine now!

**Comment by bbsixzz** [comment]
The inly problem now is music mode seems to stick for each subsequent video and if I turn it off videos appear black.

I have to reboot the app to fix it.

I'm using Invidious.

**Comment by stonerl** [comment]
Would you be so kind and open another issue?

I'm closing this one.
