### ISSUE TITLE
Airplay button does not appear with AVPlayer on iOS

### ISSUE THREAD

**Issue by jdoe29103** [yattee/yattee#489]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

If I use the AVPlayer there is no option to use airplay.

### Expected Behavior

My understanding is that AVPlayer supports airplay

### Device & OS Version

iPhone iOS 16.4.1

### App Build

1.4.4 (build 148)

### App Settings

I am signed into my Invidious server. Settings are almost all default.

**Comment by arekf** [comment]
It is not supported in 1.4.4. It is supported since 1.4.5 (currently in TestFlight)
