### ISSUE TITLE
Captions show when disabled

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#490]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

https://github.com/yattee/yattee/assets/47334163/bc75dd3e-4077-493d-ab16-914322e873af

### Expected Behavior

To not show.

### Device & OS Version

iOS 16.5

### App Build

153

**Comment by Umpaaa** [comment]
Same issue. Hitting "disabled" again does turn them off for the current video though just fyi

**Comment by ooosssay** [comment]
Same issue with me and yes disabling again does temporarily fixes the issue.
