### ISSUE TITLE
Home no longer works

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#497]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When viewing the home page, it's completely blank. I've tried updating the favorites list with different items, and no matter what's selected, the home page remains blank.

### Expected Behavior

The home page should not be blank.

### Device & OS Version

iPhone 8+, IOS 16.5

### App Build

1.4.5 build 155

### Screenshots, Videos and other files

![IMG_0170](https://github.com/yattee/yattee/assets/52843537/3c2d49b8-18db-4a9b-b499-95d04cdbcb03)

**Comment by arekf** [comment]
Can you attach a screenshot of your home settings?

**Comment by Insprill** [comment]
![image](https://github.com/yattee/yattee/assets/52843537/c93dca8d-0b36-4dbd-8ea8-240db299111b)

**Comment by arekf** [comment]
You need to toggle "show favorites" checkbox.

We need to improve design of those settings as it may be confusing

**Comment by Insprill** [comment]
Oh I see, yeah that's very confusing. Thank you! Should this be left open until the UX is improved?
