### ISSUE TITLE
Subscriptions view redesign

### ISSUE THREAD

**Issue by arekf** [yattee/yattee#50]
1) Show as list of channels links
2) Show as list of channels videos (like favorites)
3) Only display new videos

**Comment by fabcoo** [comment]
It would be a great addition to this app, I think it's the only thing I missed from the official one on tvOS, sometimes I like to scroll through my subscribed channel list just to get on a channel and check their latest videos. Implementing this would be the final step to definitely ditch the official one!

Keep doing a great job, your app is awesome!

**Comment by nobaraos12** [comment]
this would be great! but allow people to chose to enable this option or not

**Comment by arekf** [comment]
This has been implemented in 1.4.3
