### ISSUE TITLE
The sound volume is not constant

### ISSUE THREAD

**Issue by Anertz** [yattee/yattee#502]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I have tried both Invidious and Piped, as well as mpv and AVPlayer, but the volume level of the videos is strange compared to the official apps and others.
It sounds as if the sound pressure is suppressed and the volume is dynamically changing, although only slightly.

### Expected Behavior

Volume and sound pressure should be correct and constant as in the originals.

### Device & OS Version

iPhone12 iOS16.5

### App Build

155

### App Settings

Invidious and Piped settings

**Comment by stonerl** [comment]
I think the issue here is that the official YT app does some normalization to keep the volume at a constant level across videos.

So technically not a bug in Yattee.
