### ISSUE TITLE
URL scheme isn't functional

### ISSUE THREAD

**Issue by timonus** [yattee/yattee#506]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

The "Share to Yattee" extension and Shortcut both reference the yattee:// URL scheme, but neither actually works.

### Expected Behavior

You must implement the app delegate or scene delegate methods to handle URLs received by your app.

### Device & OS Version

iPhone 14 Pro

### App Build

iOS 16

**Comment by arekf** [comment]
Hey, not sure if this was a bug in previous builds, but I just tested and the urls formed like this open fine for me
```
yattee://https://www.youtube.com/watch?v=lNsl1RhCPyQ
yattee://www.youtube.com/watch?v=lNsl1RhCPyQ
yattee://watch?v=lNsl1RhCPyQ
```

Let me know if there's still some problem I am not aware of

**Comment by stonerl** [comment]
@timonus Does this still happen with the latest build (181)?

I also tested it and it works.

**Comment by timonus** [comment]
@stonerl @arekf nope, still not working. Here's what I see https://github.com/yattee/yattee/assets/522951/51acab58-0a65-406c-9ff8-cc12956f5c04. Y'all don't implement the app delegate method for handling these links afaict. Might put up a PR to add it if I can.

**Comment by timonus** [comment]
I think this should do it but didn't take the full time to get a build working on device https://github.com/yattee/yattee/pull/645.
