### ISSUE TITLE
While in a Context Menu pressing on the area of a video in the background, the video will open.

### ISSUE THREAD

**Issue by ooosssay** [yattee/yattee#510]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

After opening the menu for a button then attempting to close it by pressing on background in which it so happens to be on a thumbnail of a video it will open the video.
Steps:
Hold pressing on a button to open its contexts menu
Then press on a video in the background
The video will open

### Expected Behavior

 When dismissing the menu and just so happen to be pressing on a video the video should not open up and nothing else should not happen except closing out of the menu.

### Device & OS Version

iPad, 16.2

### App Build

155

**Comment by ooosssay** [comment]
https://github.com/user-attachments/assets/0bb3c0a1-8031-40ac-a48c-bc1994f8c7f0

**Comment by stonerl** [comment]
Is this still an issue with the latest TestFlight build?
