### ISSUE TITLE
Option to cast to SmartTV/chromecast

### ISSUE THREAD

**Issue by Umpaaa** [yattee/yattee#511]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

New feature

### Describe the feature

I’d like to cast videos from yattee to my LG TV or a chromecast (like Youtube, Netflix… have the option to). Airplay or screen-mirroring doesn’t seem to be working.

**Comment by Umpaaa** [comment]
issue on my end, sorry. Airplay does work when using AVPlayer (I was using MPV), so no need for cast option (unless you would want 1080p+)

**Comment by jbergquist** [comment]
Chromecast support would be a really nice thing to have. I don't have a clue how hard it would be to implement but I find myself at a friend or an office location that only have chromecast support in their devices.
