### ISSUE TITLE
No thumbnails in Yattee

### ISSUE THREAD

**Issue by BulldozerPete** [yattee/yattee#514]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I don't see any thumbnails in Yattee.

### Expected Behavior

Would like to see thumbnails.

### Device & OS Version

tvOS latest

### App Build

latest

### App Settings

configuered to my local INVIDIOUS on http://192.168.178.3:3000

### Crash log

n/a

### Screenshots, Videos and other files

n/a

**Comment by BulldozerPete** [comment]
Have found #354 and changes the docker yaml with 

`    environment:
      INVIDIOUS_CONFIG: |
        external_port: 443
        domain: whatever.it.is`

**Comment by MatthiasGrandl** [comment]
@BulldozerPete try adding `https_only: true` . It was required for me.

**Comment by MatthiasGrandl** [comment]
Ah wait, you are not using https, so your INVIDIOUS_CONFIG is all wrong.

**Comment by BulldozerPete** [comment]
Okay, but I wasn’t even woking before.

**Comment by MatthiasGrandl** [comment]
have you tried:

```
INVIDIOUS_CONFIG: |
        domain: 192.168.178.3
        external_port: 3000
```

not sure if this works or even is necessary, but it's highly likely that your invidious instance is just misconfigured. also make sure you restart invidious when you make those changes.

**Comment by BulldozerPete** [comment]
It works!

Maybe this hint needs to be updated to the documentation.
