### ISSUE TITLE
Yattee homepage blank, doesn't load

### ISSUE THREAD

**Issue by echeoquehaii** [yattee/yattee#516]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Hi lovely devs!

I have been struggling for a while with setting up Yattee and haven't found a solution yet, so I finally decided to open an issue here, sorry for this! I think I'm missing something in the set up but I don't understand what.
I've tried both installing Yattee normally, and from Brew.

When I start Yattee I just see this, I also attach a screen of the settings. Also trying to open any video directly, or local files, doesn't help at all. Even tried with a Invidious Instance account.

What am I missing?

### Expected Behavior

Yattee should load homepage, show trending videos, favourites and so on, and of course play videos!

### Device & OS Version

Mac OS 13.4.1

### App Build

1.4.5 (155)

### Screenshots, Videos and other files

<img width="631" alt="Screenshot 2023-07-13 at 20 15 58" src="https://github.com/yattee/yattee/assets/32939683/813e47c9-83be-4154-8883-1cec367eb5a4">

<img width="1103" alt="Screenshot 2023-07-13 at 20 15 32" src="https://github.com/yattee/yattee/assets/32939683/7b4afb7b-83f7-4a97-95f5-4d87529108e4">

**Comment by maboroshin** [comment]
Are you successful in searching for videos?

**Comment by arekf** [comment]
It should probably be enough to open sidebar with button on the top bar or keyboard shortcut cmd+option+s

**Comment by echeoquehaii** [comment]
Ohh yes, I knew it was something stupid! Thank you so much.

Actually the sidebar button doesn't work. But I could open it from the dropdown, and with the keyboard shortcut.

I think we can close this now, unless you want to keep it open to debug the not working sidebar button.
