### ISSUE TITLE
iOS (bug: UX, or documentation?) Cannot consistently add video to favorites

### ISSUE THREAD

**Issue by jwmh** [yattee/yattee#518]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

i cannot figure out how to add/remove a video to/from my Favorites.
i also do not see any obvious “favorites” tab/area in the app.

### Expected Behavior

There would be an obvious menu woth option “add to favorites”,
that is *always* available:
- within the video-watching UI
- and also
- in the History/recent videos UI

*(tangent, all user data should be exportable/re-importable…
… see NewPipe on Android (F-Droid appstore) for inspiration.
)*

### Device & OS Version

iPhone, iOS 15.7.5

### App Build

155

**Comment by jwmh** [comment]
P.S.
I am wondering if this is a translation/language issue?

“Favorites” in english 
≠ (does NOT equal)
“history/subscription/trending”

I found ONE video — ONCE — that I could “add to Favorites.”

Now I am unable to do it again.

**Comment by arekf** [comment]
There is currently no functionality to add videos to favorite. If you are signed with Invidious/Piped account, you can create a playlist and add videos there. Then last used playlist will appear in the context menu.
