### ISSUE TITLE
Invidious not refreshing subscriptions 

### ISSUE THREAD

**Issue by Jenni32222** [yattee/yattee#52]
I'm on the latest beta build (1.3 build 16) v1.3-rc on both my Apple TV and iPhone, my subscriptions don't seem to refresh automatically and also not when done manually. My subscriptions on the Invidious site do change.

**Comment by Jenni32222** [comment]
When using your curl request, I get the following:
```

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by arekf** [comment]
Try:

`curl -L 'https://<instance address>/api/v1/auth/feed' --cookie 'SID=<SID Cookie>'`

**Comment by Jenni32222** [comment]
Sorry forgot the https :)

I get a list with video's which I suppose means that the cookie indeed works?

**Comment by arekf** [comment]
Returned list of videos is used by Yattee to display your subscriptions. Does the returned list match what you can see in Yattee or when using Invidious via web browser?

**Comment by Jenni32222** [comment]
No it does not match, video's coming from curl seem to be newer.

**Comment by arekf** [comment]
If your instance is visible to public, can you create an account and send me details here or on my email so I can debug?

**Comment by Jenni32222** [comment]
Sure, coming your way in your mail.

**Comment by arekf** [comment]
It works fine with me using your instance and account details provided - my subscriptions are refreshing with new videos.

My last guess is that the issue is connected somehow with the channels you're subscribed to. In this case you can send me an example of channel that is not updating or you can try removing and adding your account again to check if this helps.

**Comment by Jenni32222** [comment]
I guess this had something to do with the postgres issue filling up the video tables, making Invidious unstable. Thanks for your help anyway,
