### ISSUE TITLE
Incorrect audio language - Invidious

### ISSUE THREAD

**Issue by Umpaaa** [yattee/yattee#523]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When watching a video with multiple audio languages, there's no way to select which language gets played (i.e. Mr.Beast video). This seems to have been an issue for Piped instances [#519](https://github.com/yattee/yattee/issues/519) and looks like this issue has been fixed, but this issue still persists with invidious instances.

### Expected Behavior

Always use original language or give option to choose language.

### Device & OS Version

iPhone 14 Pro, IOS 16.5.1c

### App Build

157

**Comment by steilerDev** [comment]
This happens to me as well - interestingly enough, when watching the same video on invidious, a different (expected) audio track is played.

**Comment by arekf** [comment]
I could not find a way to fix it with current release of Invidious - we probably need to wait for this issue to be fixed: https://github.com/iv-org/invidious/issues/2007

**Comment by Skyluker4** [comment]
To add on, using AVPlayer or MPV on the stream quality setting fixes this. Using an instance like https://yewtu.be/ does not fix it, even though it has options for audio tracks in the web player (they're using a [custom backend](https://github.com/unixfox/invidious-stripped-down) for certain paths to get them). Is there somehow a way to read the audio track from the stream preset and make it work in MPV?

**Comment by HazWard** [comment]
I’ve encountered the same issue and switching from MOV to AVPlayer fixed it for me. I’m running a private instance (self-hosted) so I can’t really share a specific link but this is the YouTube video that triggered this for me: https://www.youtube.com/watch?v=JeH5Kvf2CC0

**Comment by stonerl** [comment]
@HazWard which audio language do you hear? I tested it with my self-hosted Invidious instance. The Audio language is English for me in the video you shared.

**Comment by HazWard** [comment]
> @HazWard which audio language do you hear? I tested it with my self-hosted Invidious instance. The Audio language is English for me in the video you shared.

I think an update to the backend was enough to resolve this since I haven't encountered this ever since.

**Comment by stonerl** [comment]
Okay. Closing this one.

**Comment by craftycorvid** [comment]
I’m seeing this issue happening again with the latest Yatte and latest invidious.
Switching to stream still fixes it, at the cost of video quality.

**Comment by tgotwig** [comment]
This issue happens very often the last days 🫤
Getting original english video mostly in german or rarely some other language 🤯
