### ISSUE TITLE
Subtitles don’t work

### ISSUE THREAD

**Issue by evanpaul14** [yattee/yattee#526]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Even when captions are enable nothing shows up.

### Expected Behavior

Captions display.

### Device & OS Version

iPhone iOS 17

### App Build

155

### Screenshots, Videos and other files

[https://files.catbox.moe/116qkk.mov](https://files.catbox.moe/116qkk.mov)

**Comment by arekf** [comment]
Hi, thank you for report @evanpaul14 and the fix to MPVKit @karelrooted
I've updated the dependency and it should work fine now in just published build 169.
