### ISSUE TITLE
No thumbnails on own invidious instance

### ISSUE THREAD

**Issue by arulagrawal** [yattee/yattee#53]
I don't see any thumbnails when I use my own invidious instance. Using the newest release of yattee.

**Comment by arulagrawal** [comment]
Okay I'm stupid I think it was related to https_only option in invidious

**Comment by paulmorabito** [comment]
@arulagrawal I’m having the same problem and have tried setting https_only to both true ands false and thumbnails never load. Are you able to share any other settings you might have changed?

**Comment by arekf** [comment]
@paulmorabito Probably you need to set:
`external_port: 443`
if your instance is https, or
` external_port: 80`
if is http

**Comment by paulmorabito** [comment]
Thanks for replying. I tried setting external_port but it seems to still be not working. My container defaults to port 3000 but I redirected to 3009. I tried both 3000 and 3009 and in both cases, I am getting thumbnails on the WWW version but not Yattee.

**Comment by arekf** [comment]
Check what is returned by the API:
`https://instance-url/api/v1/videos/yXohcxCKqvo`
It should generate valid thumbnail links in `videoThumbnails` section. Check if you can open the generated thumbnails links in your web browser.

**Comment by paulmorabito** [comment]
It produces a relative path which if I append to the URL (http://192.168.1.x:3009/<path>) loads the main WWW page.

An example entry is:

{"quality":"maxres","url":"/vi/XozFiqE3oMk/maxres.jpg","width":1280,"height":720}

Should there be a hostname and port in the above string? If so, how can I add because I already set external_port to be 3009.

**Comment by icclau** [comment]
I am having the same issue with the thumbnails. I rebuilt my Invidious docker container with 

  ports:
      - "80:3000"
https_only: false
external_port: 80

What am I missing?

**Comment by bok4khru** [comment]
@paulmorabito what domain name did you choose? I tried to add http://x.x.x.x and external_port: 80 and thumbnails are still not loading. Appreciate your help

**Comment by paulmorabito** [comment]
> @paulmorabito what domain name did you choose? I tried to add http://x.x.x.x and external_port: 80 and thumbnails are still not loading. Appreciate your help

My domain is the local IP (192.168.1.x) to access the server and port (3009) is also the port its accessible on from that address.

**Comment by bok4khru** [comment]
@paulmorabito Thank you for sharing. I've tried all options on config.yml, no avail. It is strange that thumbnail loads for history but not for feed.

**Comment by bok4khru** [comment]
@arekf I tried the api url.
It resolves as "http://192.168.0.x/vi/yXohcxCKqvo/maxres.jpg"
However, to load thumbnail I need to change url to 
"http://192.168.0.x:3000/vi/yXohcxCKqvo/maxres.jpg"

Is this possibly due to config.yml issue?
port: 3000
external_port: 80
domain: 192.168.0.x
https_only: false

Appreciate your help

**Comment by arekf** [comment]
@bok4khru Try with `external_port: 3000`

**Comment by bok4khru** [comment]
> @bok4khru Try with `external_port: 3000`

This worked, thank you @arekf !

**Comment by victorlin** [comment]
Setting `domain` to match local IP and `external_port` to match `port` fixes thumbnails on Yattee.

However, it also breaks the ability to log in / save preferences on the Invidious client (see [Invidious FAQ: I can't log in nor save preferences!](https://github.com/iv-org/documentation/blob/ee58285ebd7627d719a17aef73d7192e5264e88a/docs/faq.md#q-i-cant-log-in-nor-save-preferences))
