### ISSUE TITLE
When sharing the url is referring to the api url

### ISSUE THREAD

**Issue by Duckbilled** [yattee/yattee#537]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When sharing in Yattee, the url that is about to be shared is the api e.g. apipiped.kavin.rocks, instead of piped.kavin.rocks

### Expected Behavior

An url with piped.kavin.rocks

### Device & OS Version

iPhone 13 Mini, iOS 17

### App Build

155

**Comment by stonerl** [comment]
This is actually fixed with the latest built (181). You can test it via TestFlight.
