### ISSUE TITLE
144p quality is auto selected even though best available is selected

### ISSUE THREAD

**Issue by arulagrawal** [yattee/yattee#54]
On my own invidious instance, 144p is selected by default when watching a video even though best available quality is selected and 1080p is available.

**Comment by Jenni32222** [comment]
I remember this being an issue with Invidious and that that feature is broken.

**Comment by arulagrawal** [comment]
Oh maybe I'll try setup a piped instance later then

**Comment by arekf** [comment]
Resolved in 1.3.1
