### ISSUE TITLE
CloudStream extensions compatibility

### ISSUE THREAD

**Issue by tvnmguy** [yattee/yattee#540]
CloudStream is an open source extensions based android/android tv app for watching movies, series, anime and others.

Extensions scraps contents from free websites like Uhdmovies, Sflix etc. We can play contents directely app's inbuilt player or allowing to watch contents via external player like VLC, mpv (copying stream link or selecting default external player within the app according to our preferences).

My humble request is don't limit Yattee to only YouTube things. Make Yattee as a powerful multi purpose software tool.

[CloudStream github repo](https://github.com/recloudstream/cloudstream)

[CloudStream Discord server](https://discord.com/invite/5Hus6fM)

[CloudStream website](https://cloudstream-on-fleek-co.ipns.dweb.link/repos/)

**Comment by arekf** [comment]
Yattee may support more video sources in the future, but this does not seem related to the linked app, I assume it was used as example. Thanks for the suggestion.
