### ISSUE TITLE
Subscription feed does not load any videos.

### ISSUE THREAD

**Issue by Diaub** [yattee/yattee#546]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When browsing subscriptions under the "feed" tab, video thumbnails, titles and authors do not load. When browsing under the "channel" tab, videos load flawlessly after selecting the desired channel. Home, Popular, and Trending categories still browse as expected.

### Expected Behavior

Videos should load in when browsing subscriptions in the "feed" tab.

### Device & OS Version

iPhone 12 iOS 16.1.1

### App Build

116

### Screenshots, Videos and other files

![Screenshot 2023-10-17 at 8 03 08 PM png](https://github.com/yattee/yattee/assets/57362393/7d66fe6c-218a-4cfe-82f8-da369a9dd613)

**Comment by arekf** [comment]
You need to provide details on the instance where this can be reproduced.

**Comment by arekf** [comment]
I just checked and this works for me fine. Is this issue something you can still reproduce now?

**Comment by Diaub** [comment]
Unfortunately, the issue is still there. However, I'm currently on build 166 and I have not updated to the latest pre-release build 169 yet as it is not available in the appstore.

**Comment by stonerl** [comment]
@Diaub is this still an issue? I also cannot reproduce this. It might have been an issue with the instance in question.

**Comment by Diaub** [comment]
This is no longer an issue.
