### ISSUE TITLE
Tapping on the search bar brings back to Home

### ISSUE THREAD

**Issue by sallyFoster** [yattee/yattee#548]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When the user taps on the search bar, the user gets brought back to home

### Expected Behavior

When the user taps on the search bar, the screen should stay on that window and allow the user to search. 

### Device & OS Version

iPhone 11 Pro Max, iOS 17.0.3

### App Build

v1.5

### Screenshots, Videos and other files

https://github.com/yattee/yattee/assets/104597302/a7c8f359-ed9f-4214-aa96-f16fc6ccdb25

**Comment by stonerl** [comment]
Does this still happen? With the latest build (181) I cannot reproduce this.

**Comment by sallyFoster** [comment]
It doesn't anymore
