### ISSUE TITLE
Broken /videos/ request for private Invidious instances

### ISSUE THREAD

**Issue by rix1337** [yattee/yattee#552]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Invidious is adding a feature toggle to allow creating private instances that force users to sign in.
This means that endpoints need to be requested using the user session.

**Yattee does this correctly for most requests, but fails when loading a video.**

For debugging/testing I built the patch from the invidious pull request: [and made it available on docker hub](https://hub.docker.com/repository/docker/rix1337/docker-utube/general) (arm image only)

Even though I am logged in to the patched invidious instance in Yattee, the following error pops up loading a video:
![Could not load video](https://github.com/iv-org/invidious/assets/9930448/97582d90-9311-405b-b260-145adaae9e2b)
Please note, that video thumbnails, details etc. are loaded as expected.

To help understand the error, I built Yattee locally and debugged the request that causes it:
The resource is loaded regularly by the Siesta Resource load() function
requestDescription	String	"GET https://HOSTNAME/api/v1/videos/e50028LAtAo"

The error is raised here: https://github.com/yattee/yattee/blob/fb84927fc8f216606ebafa048efa5df13c37415a/Model/Applications/VideosAPI.swift#L108

The reason for raising an error seems, the request results in a http 500 error with the new invidious patch applied.
<img width="384" alt="image" src="https://github.com/iv-org/invidious/assets/9930448/7ea22325-3679-4c1b-9718-4fcf2cb0aad2">

This is easily reproducible by requesting the URL when logged out for a patched invidious instance (same 500 error), with the following body:
<img width="223" alt="image" src="https://github.com/iv-org/invidious/assets/9930448/0b9cd4d8-e182-4bb3-8d1b-23c728b23cac">

The same request works, when signed in.

### Expected Behavior

**To work with private invidious instances, Yattee needs to request the videos endpoint with the session cookie.**

It apparently does use the cookie / session for most other requests, so this is hopefully easy to fix.

### Device & OS Version

iPhone 15 Pro Max

### App Build

168

### App Settings

Log into and use an invidious instance (proxy not required) that uses the new login_only parameter.

Find more details here: https://github.com/iv-org/invidious/pull/3728

### Crash log

See above

### Screenshots, Videos and other files

See above

**Comment by rix1337** [comment]
Related to: https://github.com/iv-org/invidious/pull/3728

**Comment by rix1337** [comment]
I tried to debug further but haven't found out how some requests (like thumbnails, channels and feed) get properly authenticated, while the /videos/ requests seem to skip the session cookie altogether..

**Comment by arekf** [comment]
This should add session cookie to the video requests:
```diff
diff --git a/Model/Player/PlayerQueue.swift b/Model/Player/PlayerQueue.swift
index 129e2cea..27152277 100644
--- a/Model/Player/PlayerQueue.swift
+++ b/Model/Player/PlayerQueue.swift
@@ -105,6 +105,8 @@ extension PlayerModel {
 
     func playerAPI(_ video: Video) -> VideosAPI? {
         guard let url = video.instanceURL else { return accounts.api }
+        if accounts.current?.url == url { return accounts.api }
+
         switch video.app {
         case .local:
             return nil
```
 I didn't test it so you can let me know if that worked for you.

**Comment by rix1337** [comment]
@arekf yes its working now. Thanks for the quick response and fix!

I tested a patched invidious instance as well as several unpatched ones.
Unpatched ones were of course working before and still are.
Patched instances were broken before and now work.


Eagerly waiting for a release with this 👍🏻

**Comment by rix1337** [comment]
@stonerl / @arekf 

The lastest TestFlight now works with my private instance.

But only while the Proxy Video option is turned off

Turning proxy videos on yields a new error:
![IMG_4730](https://github.com/yattee/yattee/assets/9930448/a235d6a6-92b8-431d-afbd-f80daaac4d86)
