### ISSUE TITLE
Cannot add custom instance  to Yattee

### ISSUE THREAD

**Issue by calm108** [yattee/yattee#555]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I have Individous running on Umbrel on my local network.  I can browse to the thumbnail URL link and validate that I can see and connect to my instance.  In my example it is http://umbrel.local:3420/ap/v1/videos/rr2XfL_df3o

When I attempt to add in Yatee on IOS via settings>Locations>Add a custom location  using the url:
http://umbrel.local:3420/ap/v1/  I cannot save the location as Yattee says: Connection failed

Is this a bug or am I doing something wrong?

### Expected Behavior

Conenction works

### Device & OS Version

TVos 17.1

### App Build

1.5 build 166

**Comment by stonerl** [comment]
You just need to add the address: [http://umbrel.local:3420](http://umbrel.local:3420)

**Comment by calm108** [comment]
I tried that and no luck   still says Connection Failed.

**Comment by stonerl** [comment]
Why did you rename the `/api/` endpoint to `/ap/`?

**Comment by calm108** [comment]
I did not that is a typo on my end sorry
