### ISSUE TITLE
Settings option gone after removing browsing options

### ISSUE THREAD

**Issue by sirnacnud** [yattee/yattee#56]
This is with 1.3 on iOS 14. I disabled browsing options for Favorites (I think popular and trending were also disabled), but now the settings button is gone, as well as the profile button. Only the search icon remains in the tab bar at the bottom.

The issue persists between launchs of the app.

<img width="375" alt="Screenshot 2022-01-24 at 4 53 14 PM" src="https://user-images.githubusercontent.com/579727/150818048-5ca266bc-6b09-4c68-81d4-3f8de9bb34a3.png">

**Comment by arekf** [comment]
Resolved in 1.3.1

**Comment by sirnacnud** [comment]
Thanks for the fast fix!
