### ISSUE TITLE
support for ios 12

### ISSUE THREAD

**Issue by sukualam** [yattee/yattee#566]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

New feature

### Describe the feature

i think my primary reason to use 3rd party youtube client is to make my old ipad air 1 on ios 12.5.7 useful again.

im glad found this project, but when i realized this app need ios 14, i think it contrary to my purpose.

if it minimum ios 14, it actually better to use youtube instead, coz on app store still updating, while for ios 12 is no update.

so, why not make it to minimum at least ios 12?

**Comment by stonerl** [comment]
Because most of the features, this app uses, require at least iOS 13. And even then, there are tons of issues because plenty of other features require iOS 14 or newer. So this is very unlikely to ever happen.

**Comment by arekf** [comment]
Yattee is created with SwiftUI which was available only since iOS 13. It's too complex to make it work even there so it's requiring iOS 14 for now but eventually may be increased to even higher OS version. There are no plans to make it work/keep it working on very old iOS versions.
