### ISSUE TITLE
Cannot scroll through descriptions or comments when the video is paused

### ISSUE THREAD

**Issue by sallyFoster** [yattee/yattee#567]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I cannot scroll through descriptions or comments when video paused.

### Expected Behavior

Users should be able to scroll down the video description and comments when the video is paused.

### Device & OS Version

iOS 17.1

### App Build

1.5.1-169

### Screenshots, Videos and other files

https://github.com/yattee/yattee/assets/104597302/b1acd9e2-f8a2-4f7f-b9f0-f8530b4d64d7

**Comment by stonerl** [comment]
Double tap on the video title.

**Comment by sallyFoster** [comment]
@stonerl That doesn't work for shorts 

Try it out 

URL: https://youtube.com/shorts/28T91fgkpkA?si=APTqUoG_tpS0JJCs

**Comment by sallyFoster** [comment]
@stonerl That worked. Thanks!
