### ISSUE TITLE
Error while Opening file

### ISSUE THREAD

**Issue by girish54321** [yattee/yattee#572]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

paste any YouTube link gives error.

### Expected Behavior

Play form YouTube Link

### Device & OS Version

Mac OS

### App Build

Version 1.5 (166)

### App Settings

default

### Screenshots, Videos and other files

<img width="300" alt="Screenshot 2023-11-30 at 11 16 58 AM" src="https://github.com/yattee/yattee/assets/47414322/0a796b80-666e-4f19-8741-ea5bb5a6dc50">

**Comment by arekf** [comment]
This happens if you didn't add a location being able to play YT videos.
