### ISSUE TITLE
[Feature Request] Switch Lockscreen player controls

### ISSUE THREAD

**Issue by CanIHelp101** [yattee/yattee#58]
Not sure if this is possible but having an option to resemble the native Youtube app's lockscreen controls would be nice. Currently, there are skip 15 second buttons instead of the usual skip to next video in queue buttons.
![0A0D63EE-9533-4F34-9175-86BF1D92C849](https://user-images.githubusercontent.com/91703973/152621165-9bdefdf7-6ee0-495f-ac64-d16e7d9cf24e.jpeg)
![60B18759-307F-4DDD-83C5-9351484CB97D](https://user-images.githubusercontent.com/91703973/152621167-a5b837c1-83b5-4e1c-bdae-2a5d112419de.jpeg)

**Comment by arekf** [comment]
Added as option in v1.4
