### ISSUE TITLE
I would like to see the number of downvotes on videos

### ISSUE THREAD

**Issue by sallyFoster** [yattee/yattee#581]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Improvement to existing feature

### Describe the feature

It would be great if the number of downvotes on videos were shown and not just the number of upvotes.

**Comment by arekf** [comment]
Settings > Player > Enable Return YouTube Dislike
