### ISSUE TITLE
1 hour long videos are not loading correctly

### ISSUE THREAD

**Issue by sallyFoster** [yattee/yattee#585]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

1 hour long videos load, but they cannot be interacted with. They don't play and they don't rewind. 

### Expected Behavior

1 hour long videos should play like any other video.

### Device & OS Version

iPhone 11 Pro Max

### App Build

1.5.1 (build 171)

### Screenshots, Videos and other files

URL: https://www.youtube.com/watch?v=IS4cpvvLeYo

https://github.com/yattee/yattee/assets/104597302/9b3d3ad4-1272-41ed-91e2-e76bd5b00aa8

https://github.com/yattee/yattee/assets/104597302/3d7d6481-1a8a-4042-8412-12bd91dac8fd

**Comment by stonerl** [comment]
I tried the same video and have no issues.

Which instance are you using?

Do you the proxy option?

**Comment by sallyFoster** [comment]
@stonerl I am using https://piapi.ggtyler.dev
