### ISSUE TITLE
Sometimes sound stop working in the videos

### ISSUE THREAD

**Issue by sallyFoster** [yattee/yattee#588]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Sometimes sound just stops working in the video

### Expected Behavior

The sound on videos should always work 

### Device & OS Version

iPhone 11 Pro Max 

### App Build

1.5.1 (build 171)

### Screenshots, Videos and other files

Video: https://www.youtube.com/watch?v=gZuprw5NN4o

At 3:50 the sounds stops working

**Comment by PencilNotPen** [comment]
Me too on Apple TV 4K (newest gen) on Yattee 1.5.1 build 171

**Comment by stonerl** [comment]
I assume you are using Piped as your Instance. This rather a piped bug than a Yattee bug. But it should be circumvented and fixed with conditional proxying #662
