### ISSUE TITLE
Clicking video from channel different functionality

### ISSUE THREAD

**Issue by sopans** [yattee/yattee#59]
When clicking a video directly from any page that isn't directly from someone's channel, it opens the video in a somewhat different video player than when clicking a channel, and then clicking on one of their videos. When trying to drop a video opened from a channel's page into the mini-player, it simply opens the channel's page back up. I am using Invidious.!
[image](https://user-images.githubusercontent.com/96969390/154807083-21ed3dd3-529d-417b-a110-81f99c7def0b.png) 
Video when opened from home page.

![image](https://user-images.githubusercontent.com/96969390/154807173-fc7ce9cd-0b8c-40bf-9cd5-0b1ec07e88ba.png)
Video when opened from channel page

![image](https://user-images.githubusercontent.com/96969390/154807193-5d5668ea-db6a-4ad3-9484-adea241bf265.png)
- Result when trying to minimize video opened from channel page.

**Comment by arekf** [comment]
Closing as channels UI has been changed in v1.4
