### ISSUE TITLE
[MPV] Seeking to unbuffered timestamp fails for some mp4 streams

### ISSUE THREAD

**Issue by Rbot427** [yattee/yattee#590]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

1. Open a longer mp4 video and begin playback with mpv
2. Attempt to seek to an unbuffered portion of the video (i.e. the end of a long video)
3. Observe the seek fail, leaving the video at the current timestamp

### Expected Behavior

1. Open a longer mp4 video and begin playback with mpv
2. Attempt to seek to an unbuffered portion of the video (i.e. the end of a long video)
3. Video jumps to the requested timestamp and begins playback 

### Device & OS Version

iPhone, iOS 16.6.1

### App Build

171

### Screenshots, Videos and other files

Attached below is the mpv log
[yattee-170-mpv-log.txt](https://github.com/yattee/yattee/files/13639402/yattee-170-mpv-log.txt)

**Comment by GizmoTjaz** [comment]
Same here, seeking doesn't do anything.

**Comment by stonerl** [comment]
This seems to be a general playback issue with MP4 streams.

Since Piped seems to only serves .mp4 and .webm and .mp4 has higher priority, Yattee chooses the .mp4 stream by default.

I made an PR that swaps the order of the codecs and moves .mp4 to the bottom.
