### ISSUE TITLE
[Bug] PiP mode does not respect "Music Mode" when launching other apps (PIP sometimes starts playing video)

### ISSUE THREAD

**Issue by R8s6** [yattee/yattee#617]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Before driving, I desire this routine:

1. launch Yattee, play some video
2. enable "Music Mode" (to play audio only), in order to save on cellular data
3. launch Google Maps for navigation

At step 3, yattee will undesirably go into PiP (picture-in-picture) mode and video will start playing again inside PiP, this would consume a lot of cellular data, potentially costing money.

My workaround is:

1. hit the "PiP" button so Yattee relaunches, 
2. re-launch Google Maps (or any other app)
3. this 2nd time, PiP won't engage, and from data consumption report, it appears Yattee is downloading and playing audio only in the background which is good.

### Expected Behavior

1. launch Yattee, play some video
2. enable "Music Mode" (to play audio only), in order to save on cellular data
3. launch Google Maps for navigation

PiP doesn't engage, and only audio is playing in the background

### Device & OS Version

iPhone 13, iOS 17.3.1

### App Build

1.5.1

### App Settings

Player: AVPlayer or MPV, same behaviour
Server: Piped, self-hosted
Settings: Player - Picture in Picture, different settings behave the same

**Comment by stonerl** [comment]
I cannot reproduce this on iOS 17.5 with the latest build (181)
