### ISSUE TITLE
Support with Chinese Traditional Language

### ISSUE THREAD

**Issue by rexcsk** [yattee/yattee#620]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Usability improvement

### Describe the feature

I would like to help translating Yattee with Chinese Traditional when I got time, haven't find a profile in weblate. Does it need admin to enable for me?

**Comment by arekf** [comment]
If you already have Weblate account with Chinese Traditional set as translated language in preferences (https://hosted.weblate.org/accounts/profile/) then you can go here: https://hosted.weblate.org/projects/yattee/#languages and you should see plus button to add language as in the screenshot:
<img width="964" alt="Screenshot 2024-02-27 at 14 01 03" src="https://github.com/yattee/yattee/assets/367484/7dc5a62d-e801-42a5-bbf0-a6a8137936d8">
