### ISSUE TITLE
Crash when Piped comments cannot be loaded

### ISSUE THREAD

**Issue by Insprill** [yattee/yattee#629]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When opening comments on a video where Piped failed to load the comments, the app immediately crashes.

### Expected Behavior

The app should not crash.

### Device & OS Version

iPhone 8+, IOS 16.7.7

### App Build

v1.5.1 build 174

### Crash log

N/A (?)

### Screenshots, Videos and other files

This is how the comments show in Piped, so I'm assuming there's some sort of null-reference happening
![image](https://github.com/yattee/yattee/assets/52843537/a2132a26-1a2f-444c-9a2d-d438bab3becb)

**Comment by stonerl** [comment]
@Insprill which instance are you using. I had the same issue with my private instance. I tried to debug it but now I cannot reproduce it, anymore.

**Comment by stonerl** [comment]
@Insprill in case you're able to build Yattee yourself, can can give the PR a try and report back.

**Comment by stonerl** [comment]
It does not crash anymore and shows empty comments instead. Maybe I can fix this as well.
![image](https://github.com/yattee/yattee/assets/2091312/a368ae99-5367-4a4d-90ff-9f406aacafe6)
