### ISSUE TITLE
Subtitles not working again on Apple TV with Invidious

### ISSUE THREAD

**Issue by maxcrees** [yattee/yattee#630]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Similar to #526, subtitles are no longer displaying again with the MPV player when playing YouTube videos via Invidious. This is with build 180, but this has been an issue for at least a few builds now. I remember they were working in build 169 as the previous issue mentions, but at some point they stopped working again in the same manner. I haven't changed the Invidious version in the meantime (still 2023.11.08-c5b87e3b). I can confirm the Invidious interface still displays subtitles. 

### Expected Behavior

Subtitles should be displayed when enabled and available. 

### Device & OS Version

tvOS 17.4

### App Build

180

**Comment by stonerl** [comment]
Can you give build 181 a try?

**Comment by maxcrees** [comment]
Can confirm subtitles are working again in build 181.
