### ISSUE TITLE
Music mode stuck / black video

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#649]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Music mode seems to stick for each subsequent video and if I turn it off videos appear black.

I have to reboot the app to fix it.

I'm using Invidious.

### Expected Behavior

None of the above

### Device & OS Version

iPhone 13 Mini iOS 17.4.1

### App Build

181

**Comment by ooosssay** [comment]
Video evidence 

https://github.com/yattee/yattee/assets/129241633/6f6e5555-740b-4dab-82a3-a0e0d57347ad

This was on Piped

**Comment by stonerl** [comment]
Should be fixed with 185.

**Comment by stonerl** [comment]
An addendum. If you are using Piped with a proxy, then there is not much we can do about this issue . Piped has currently a broken proxy and doesn't correctly stream the videos.
