### ISSUE TITLE
iOS: Exit full screen video when finished

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#663]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Usability improvement

### Describe the feature

When video finishes with close video and player on end set to off the screen remains black and you have to manually exit the full screen mode.

I would like the behavior to automatically exit full screen mode so I can read comments etc.

**Comment by stonerl** [comment]
Duplicate of #105
