### ISSUE TITLE
"Connection Failed" While Signing Into Piped Account

### ISSUE THREAD

**Issue by TanKot** [yattee/yattee#67]
Title Says It All..

**Comment by arekf** [comment]
This was Piped bug which was resolved, should no longer be an issue.

**Comment by TanKot** [comment]
It was resolved for me a while back 👍

**Comment by 34candos** [comment]
Am having this issue now. 
1. create an account on a piped instance
2. add the instance as a location in Yattee (using api address)
3. in the location, give the frontend url and enter credentials.
4. connection failed
Am I missing something?
