### ISSUE TITLE
Can't sideload with AltStore: invalid characters

### ISSUE THREAD

**Issue by migmit** [yattee/yattee#670]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

1. Download IPA from Releases (tried both 1.5.2 pre-release and 1.5.1)
2. Attempt to install it with AltStore

Result: Error thrown, titled "Install Failed" with a subtitle "AltStore.AppleDeveloperError 3009" and body "The name “” contains invalid characters".

### Expected Behavior

Yattee installed

### Device & OS Version

iPad, latest stable iPadOS

### App Build

Not sure; probably 182?

**Comment by stonerl** [comment]
Does this only happen with Yattee or also with other apps? could be an AltStore issue …

**Comment by migmit** [comment]
uYou+ installs normally.

**Comment by stonerl** [comment]
Still an issue with 185?

**Comment by migmit** [comment]
Yes.

![IMG_1079](https://github.com/yattee/yattee/assets/2890201/4765c407-b378-438a-8eee-890fd0d63e2a)

**Comment by stonerl** [comment]
It's apparently an issue with non ASCII characters. [Error 3009 on AltStore](https://github.com/altstoreio/FAQ/blob/main/getting-started/error-codes.md#3009-the-name-for-this-app-is-invalid)

That is something @arekf needs to check.
