### ISSUE TITLE
Swipe down to close video is choppy 

### ISSUE THREAD

**Issue by ooosssay** [yattee/yattee#678]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When closing the player by swiping, the player becomes really choppy.
Open a video
Swipe down to close player 

### Expected Behavior

A smooth closing player.

### Device & OS Version

iPhone XR iOS 17.2.1

### App Build

183

### Screenshots, Videos and other files

https://github.com/yattee/yattee/assets/129241633/f5b61cee-bb3f-4a50-bcc8-14d7b30ba3d5

**Comment by stonerl** [comment]
Should be smoother with 184.

**Comment by ooosssay** [comment]
I’m just now opening Yattee and it became smoother. I don’t know why but the update didn’t take affect before. Closing
