### ISSUE TITLE
Often poor video quality (despite fast and stable internet speed), and playback issues once 1080p/720p is picked manually

### ISSUE THREAD

**Issue by stripedgoat** [yattee/yattee#68]
As the title says, I have a 100Mbit connection (with speed measurements confirming it), yet the app loads poor quality video playback a lot of times.

I would really love to have a playback option to choose 1080p, and let that be the ONLY steam. I don't care if it sometimes lags, I would be happy for such an option. Stable quality choice for a default playback quality (right now only Adaptive is available).

Another thing I noticed, when I manually switch the playback quality to 1080p or 720p, it switches only after about a minute into the video, and once it switches, the playback becomes choppy every few moments. The video literally pauses for a second or two, while the audio keeps playing fine. Then it catches up. Then again comes the paused video...repeating this all the way until the end of the video.

**Comment by arekf** [comment]
High quality playing performance issues should be resolved with new player ([v1.4](https://github.com/yattee/yattee/releases/tag/v1.4-alpha.1)) - closing this issue.
