### ISSUE TITLE
Audio and video becomes desynchronized

### ISSUE THREAD

**Issue by ooosssay** [yattee/yattee#690]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When scrubbing through the video there would be a long pause then video will show up and audio but audio will play according to the current timestamp but the video will freeze or continue from the beginning.

### Expected Behavior

Both audio and video be synchronized.

### Device & OS Version

iPhone, iOS 17.2.1

### App Build

185

### Screenshots, Videos and other files

[yattee-185-mpv-log.txt](https://github.com/yattee/yattee/files/15419487/yattee-185-mpv-log.txt)

**Comment by stonerl** [comment]
Oh, you are using a piped proxy, that might be the main problem.

**Comment by ooosssay** [comment]
Yeah it happened again after the setting change

**Comment by ooosssay** [comment]
I turned off proxy and it seems that it’s working now

**Comment by stonerl** [comment]
> Yeah it happened again after the setting change

Then set it back to `no`.

> I turned off proxy and it seems that it’s working now

Yeah, the Piped proxies are broken ATM. I would leave it turned off. Yattee automatically enables it for certain content, e.g., music, when it detects that the video is restricted by Google.

**Comment by stonerl** [comment]
Note to myself. Implement:

`--initial-audio-sync=<yes|no>`
