### ISSUE TITLE
tvOS - upcoming tag missing in subscriptions

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#693]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Missing in subs, shown in channel feed.

![IMG_9344](https://github.com/yattee/yattee/assets/47334163/bb05c52d-490c-4e2d-9bac-261231a0196a)

### Expected Behavior

To be shown in subs feed.

### Device & OS Version

Apple TV A2169 tvOS 17.5

### App Build

174

**Comment by stonerl** [comment]
Is this still an issue with the latest TestFlight version?

**Comment by bbsixzz** [comment]
Fixed! Cheers
