### ISSUE TITLE
Scrambled CJK text in comment section

### ISSUE THREAD

**Issue by leana8959** [yattee/yattee#703]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

In the comment section, comments written in CJK languages are shown in [Mojibake](https://en.wikipedia.org/wiki/Mojibake). Even text in European languages are shown incorrectly (accented vowels in French, for instance).

I search the issue tracker and found #443, which is similar. However, I do not have issue with CJK characters in the search bar nor in video titles.

The comment in CJK also shows correctly on my invidious instance.

### Expected Behavior

The comment should be readable. 

I suspect the text is not decoded as UTF-8 at all, if someone could lend me a hand, I'm willing to help to resolve/test this issue, I do not have much experience developing for iOS, though I do have a mac (and an iPhone, ofc).

### Device & OS Version

iPhone, 17.5.1

### App Build

Yattee 1.5.1 (build 174)

### App Settings

I have kept my settings for quite a while and I don't remember, sorry.
Is there a way I could back up my current settings to a "profile" and then switch to a clean profile to test whether the issue persists ?

### Screenshots, Videos and other files

<details>

<summary>Some examples</summary>

![Traditional Chinese](https://github.com/yattee/yattee/assets/87855546/be66b9f5-2348-4103-83be-811037d5bd79)

![French](https://github.com/yattee/yattee/assets/87855546/835894d7-aa6c-4c0c-a7b2-424f7c9599b9)

</details>

**Comment by stonerl** [comment]
This has already been fixed. You might try the TestFlight build.
