### ISSUE TITLE
Proposal to Standardize Release Tagging Using Semantic Versioning

### ISSUE THREAD

**Issue by cdwmhcc** [yattee/yattee#708]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Improvement to existing feature, Usability improvement

### Description

Dear Yattee Developers,

I have noticed an inconsistency in the version tagging within the releases section that could potentially confuse users trying to track changes or understand the progression of releases.

### Examples of Current Version Tagging

Here are a few examples from the Releases page that illustrate the current inconsistency in version naming:

- 1.5.2-186
- 1.5.2-185
- 1.5.1

### Suggestion

I recommend standardizing the version numbering format by adopting [Semantic Versioning (SemVer)](https://semver.org/):

- 1.5.2-beta.2
- 1.5.2-beta.1
- 1.5.2-alpha.1
- 1.5.2-dev
- 1.5.1

### Conclusion

I hope you will consider this proposal to standardize version numbering. I believe adopting SemVer can significantly streamline development workflows and help both contributors and users to better understand the significance of each release.

Thank you for considering this suggestion, and for your continued work on this valuable project.

**Comment by stonerl** [comment]
Well, this is something @arekf has to decide. But the releases, including the build numbers, are dev releases, and marked as such in the release tab.

To mark something as alpha or beta would mean that there is a roadmap, as to what should surface or be implemented in a certain release. But this is not how Yattee development works right now.

I work on a feature I'd like to be in the app or fix bugs. However, there is no planing behind this on my side. So what would change for the user if the versioning scheme would change?
