### ISSUE TITLE
[Bug] [iOS] app crash after video playback

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#71]
yattee app gets **crashed and terminated after the video playback ended**.

in my case, this issue happened in fullscreen mode. This error occurs to me at least 2 out of 5 times of the app use.
and **sometimes, after the end of the video, the app goes to the Favorites page [this problem happened at the normal portrait mode]**.

yattee version: v1.3.2
iOS version: 15.4

**Comment by bachig26** [comment]
@arekf this bug is still in the v1.3.4 (Latest Release), the app crashes at every time at the video playback end. I just found out now after watching a video till the end and crashes at every video playback end.

**Comment by arekf** [comment]
> @arekf this bug is still in the v1.3.4 (Latest Release), the app crashes at every time at the video playback end. I just found out now after watching a video till the end and crashes at every video playback end. ps. I haven't checked the crash in 1.4-alpha4 yet.

Attach a crash log, otherwise I cannot tell what is causing it.

**Comment by bachig26** [comment]
> Attach a crash log, otherwise I cannot tell what is causing it.

[crash log.zip](https://github.com/yattee/yattee/files/8757996/crash.log.zip)

There will be 3 crash log files in this zip which was taken at the time my earlier comment above.
