### ISSUE TITLE
App crashes when using MPVPlayer

### ISSUE THREAD

**Issue by michaelrogers0** [yattee/yattee#712]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

App immediately crashes when launching using the latest testflight version which is v1.5.2 (build 187). Then if I switch back to the app I can then see the interface and interact with it.

### Expected Behavior

App to launch without crashing as it did in the previous testflight version.

### Device & OS Version

iPhone Xs Max, iOS 17.5.1

### App Build

187

### Crash log

I don't have a "Privacy" area to grab logs from.

**Comment by stonerl** [comment]
Does this happen consistently when you start app, or only on the first start after the update?

**Comment by skyer1a** [comment]
im on macOS 15.0 (beta 3) and i have just installed the app and it crashes instantly
the build im using is build 187 (1.5.2)

**Comment by xa4hf8** [comment]
OS Version: macOS 14.5 (23F79)
Crashed Thread: 7  Dispatch queue: com.apple.root.user-initiated-qos

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Termination Reason:  Namespace SIGNAL, Code 6 Abort trap: 6
Application Specific Information: abort() called

[Yattee 1.5.2 crash log.txt](https://github.com/user-attachments/files/16310636/Yattee.1.5.2.crash.log.txt)

**Comment by jameshy** [comment]
Same crash here as @xa4hf8.

First time running Yattee-1.5.2-macOS.zip on macOS Sonoma 14.5.

[Yattee-2024-07-19-123839.ips.txt](https://github.com/user-attachments/files/16310866/Yattee-2024-07-19-123839.ips.txt)

**Comment by uofr2023** [comment]
when I use mpv I got same issue, so I remove app to trash and then remove `Yattee` folder under ~/Library/Containers.
and reinstall it. then yattee can re-launch. 
Hope it was useful.

**Comment by xa4hf8** [comment]
⚠️ The `Helgrind` module in [Valgrind](https://valgrind.org/) can sometimes detect race conditions that might cause a crash on one architecture but not another.

https://github.com/LouisBrunner/valgrind-macos

**Comment by stonerl** [comment]
@xa4hf8 they don't support arm right now.

**Comment by xa4hf8** [comment]
@stonerl - It seems to be crashing only on the ARM platform, so I presumed that you have an Intel Mac if you marked it `unreproducible`.  Are you saying that you have an ARM device and it does not crash?  —If it does not crash on all ARM devices that run the current OS then you need to acquire more specific information from the victims.  In that case, people should edit their crash report to include CPU model & physical memory.  Also note that ARM support in Valgrind is  in progress:

https://github.com/LouisBrunner/valgrind-macos/issues/56

**Comment by stonerl** [comment]
@xa4hf8 I have an M2 Pro. But I need to check if this crash also happens on my machine. Haven't used Yattee on Mac lately.

**Comment by stonerl** [comment]
I fixed a possible (startup) crash with #748. I'm also able to reproduce the MPV crash @uofr2023 mentioned. But I wonder if this is an issue with macOS 15. MPV uses OpenGL, and it has been deprecated for a long time by Apple.

@jameshy, @uofr2023, @xa4hf8, @michaelrogers0, @skyer1a
 
Can you guys/galls give the latest build (190) a try and report back, whether you still have the startup crash and if it also crashes when playing back a video with MPV? Moreover, it would be interesting to know which OS release you are using.

**Comment by stonerl** [comment]
I think I found the problem. It is the built-in LuaJIT in MPV.
