### ISSUE TITLE
App fails to play any videos

### ISSUE THREAD

**Issue by michaelrogers0** [yattee/yattee#713]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When attempting to play any video I get the error message "Failed loading video. Operation Stopped".

### Expected Behavior

For the video to play correctly as it did in the previous testflight version.

### Device & OS Version

iPhone Xs Max, iOS 17.5.1

### App Build

187

### Crash log

I don't have a "Privacy" section to grab logs from.

**Comment by bigl00z3** [comment]
It musst be the same issue that affected [Newpipe](https://github.com/TeamNewPipe/NewPipe). A change by YouTube. It probably needs a similar fix as [they did](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) (the fixed version was released today).

**Comment by stonerl** [comment]
I'm closing this one since it isn't a Yattee issue but rather one that stems from YouTube's recent crack down on third party apps/instances.
