### ISSUE TITLE
problem seeing the image preview

### ISSUE THREAD

**Issue by fatez** [yattee/yattee#714]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

when I open yattee I don't see a preview of any video. The videos start and work fine but the preview remains an empty gray box

### Expected Behavior

I expect to see the preview image of the videos

### Device & OS Version

iPhone 15 Pro Max 17.5.1, iPad 17.5.1 Pro 11 M4

### App Build

1.5.2 build 187

### Screenshots, Videos and other files

![IMG_0024](https://github.com/user-attachments/assets/6c1bface-8c18-4ce4-8d35-044dee489a9a)
![IMG_1890](https://github.com/user-attachments/assets/29d672eb-2623-4697-a4e3-67a98f188c62)
![IMG_1889](https://github.com/user-attachments/assets/a697ba3e-eee6-4af4-a81e-33f1a5c2c3ea)
![IMG_1888](https://github.com/user-attachments/assets/91f90a2c-bde8-42be-8b44-fbe37957aeac)

**Comment by stonerl** [comment]
Not really a Yattee issue, but rather a problem with the instance being overloaded.

That happens particularly on bigger instances with many users.

**Comment by fatez** [comment]
> Not really a Yattee issue, but rather a problem with the instance being overloaded.
> 
> That happens particularly on bigger instances with many users.

I understand and I thank you.
Unfortunately, I don't think that's the problem, I only have one user (me)

**Comment by stonerl** [comment]
Are you using https or http?

**Comment by fatez** [comment]
HTTP

**Comment by stonerl** [comment]
That is the problem. Currently, HTTPS is necessary for the thumbnails to load.

**Comment by fatez** [comment]
> That is the problem. Currently, HTTPS is necessary for the thumbnails to load.

I get it!

Then I thank you very much for the tip.
Unfortunately I don't know where to start to get invidious to go https... I have tried several guides but since I don't have a public domain I can't get it to work with ssl certificate.

thanks again

**Comment by sallyFoster** [comment]
@stonerl 

On the instance that I am connected on is doing the same. The instance is: https://inv.altesq.net/

**Comment by fatez** [comment]
> @stonerl
> 
> On the instance that I am connected on is doing the same. The instance is: https://inv.altesq.net/
> 
> It is a small instance just 2 registered users, and it uses https

Same issue here with another local site in https (self hosted and signed certs)

**Comment by stonerl** [comment]
For the thumbnails to load, the invidious instance must be properly configured.

You need to set the `external_port`, the `domain` and `https_only = true`.

Also invidious needs to run begins reverse proxy.

**Comment by stonerl** [comment]
One more thing. Could you try to set the thumbnail quality to medium and check whether they are displayed?

**Comment by stonerl** [comment]
@sallyFoster as said in the other issue, the site is improperly configured.

@fatez see my last comment. Furthermore, if you are using self-signed certificates, or do not run on a standard port (443) there could also be problems.

**Comment by stonerl** [comment]
Closing this one, since this is a server configuration issue.
