### ISSUE TITLE
Player lower bar is gray out

### ISSUE THREAD

**Issue by gferreroferri** [yattee/yattee#719]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Lower part of the player bar showing video duration and more options is gray out instead of white. See screenshot

![image](https://github.com/user-attachments/assets/44c78ac3-cff7-4e22-96b5-6d669283be78)

### Expected Behavior

It should be white colour

### Device & OS Version

iPhone, iOS18

### App Build

174

### Screenshots, Videos and other files

![image](https://github.com/user-attachments/assets/6db68111-9e37-4d3d-b533-be0ec134b811)

**Comment by stonerl** [comment]
This is with AVPlayer?

**Comment by gferreroferri** [comment]
Yes

**Comment by gferreroferri** [comment]
Ok.  I will wait till final iOS release and if still there I can reopen the ticket

**Comment by stonerl** [comment]
That only happens when you have "Use System Controls with AVPlayer" enabled.

Even if this stays the same with the final iOS 18 release, there is nothing we can change about that, since we cannot change the appearance of the system controls.
