### ISSUE TITLE
Arabic comments showing weird characters 

### ISSUE THREAD

**Issue by wael-t** [yattee/yattee#723]
### Guidelines

- [x] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I connect Yatte to my self-hosted invidious instance, Arabic comments are not working properly, Arabic letters are replaced with some weird characters. 

### Expected Behavior

Comments section should show Arabic words properly. 

### Device & OS Version

Iphone 13 min, latest ios

### App Build

174

### Screenshots, Videos and other files

![IMG_0792](https://github.com/user-attachments/assets/4f7f0f3d-308d-4fac-83ac-6feb9be84706)

**Comment by stonerl** [comment]
Can you give the latest TestFlight built a try? That should have addressed the issues with the comments…

**Comment by wael-t** [comment]
Confirmed, Arabic comments are showing with no issue in the TestFlight built.

**Comment by stonerl** [comment]
Closing this one then.
