### ISSUE TITLE
No thumbnails show up

### ISSUE THREAD

**Issue by thickmelon** [yattee/yattee#725]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Used a self hosted instance of invidious. Videos play just fine. However, I can't get any thumbnail for any videos shown. 

### Expected Behavior

have every thumbnail of every video pulled from said invidious

### Device & OS Version

iPhone, iOS 17.5.1

### App Build

174

### Screenshots, Videos and other files

![IMG_2011](https://github.com/user-attachments/assets/86427d07-829a-4e79-bd01-d6798a78ec38)

**Comment by sallyFoster** [comment]
On the instance that I am connected on is doing the same. The instance is: https://inv.altesq.net

**Comment by stonerl** [comment]
@sallyFoster the reason this does not show you thumbnails is, that they did not properly configure the server. `https://inv.altesq.net:3000/vi/vFOIauPQ5XI/maxres.jpg` Port 3000 is the internal docker port.

**Comment by stonerl** [comment]
@thickmelon do you run your own instance or use a public one?

**Comment by thickmelon** [comment]
This is self hosted, and I tunneled it with cloudflared.

2024년 8월월 16일 (금) 10:12 오후, Toni Förster ***@***.***(mailto:2024년 8월월 16일 (금) 10:12 오후, Toni Förster <<a href=)> 작성됨:

**Comment by stonerl** [comment]
Then please check your invidious settings:

```
external_port: 443
domain: sub.domain.org
https_only: true
```

Also, make sure you're having a valid SSL certificate.

**Comment by sallyFoster** [comment]
@stonerl It is not showing the icons of subscriptions now 



 ![image](https://github.com/user-attachments/assets/faaf90a3-9df0-4a36-987e-c368cebe9f0d)

**Comment by stonerl** [comment]
Different issue. They will show up when after you watched a video from the channel or click on the channel from the list.

**Comment by sallyFoster** [comment]
@stonerl Why is that?

**Comment by stonerl** [comment]
Because either options query the channel thumbnail. The channel sub view only shows those that are already cached.

**Comment by stonerl** [comment]
Closing this one, since it is a server configuration issue.

**Comment by woody-lw** [comment]
This is still an issue, tried everything with the invidious instance.
Somehow via browser all Thumbnails are loading, though not via Yattee, so should be an Yattee issue
