### ISSUE TITLE
[enhancement] [iOS] Menu option for Instances in Settings

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#73]
This issue is the request for enhancement to the settings by **implementing a menu option for the Instances instead of the current look, if one has many Piped and Invidious APIs the current settings look cluttered and messy**.

Desired Behaviour:
_A new Menu option for instances like the current Browsing and Player options_.

_**Settings > Instances > Piped > [List of Piped APIs URL]
Settings > Instances > Invidious > [List of Invidious APIs URL]
Settings > Instances > [+ Add _Instance...]**_

yattee version: v1.3.2
iOS version: 15.4

**Comment by arekf** [comment]
This is no longer relevant as instances are in separate submenu
