### ISSUE TITLE
[Bug] [iOS] three Sections "Subscriptions; Popular; Playlists" not working

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#76]
The Sections such as "**Subscriptions**; **Popular**; **Playlists**" are not able to enable or use even after selecting them in the settings.

yattee version: v1.3.2 & v1.4-alpha.1
iOS version: 15.4

**Comment by arekf** [comment]
For Subscriptions you need to login to an account (Piped or Invidious). Popular and Playlists work only with Invidious.

**Comment by bachig26** [comment]
> 



> For Subscriptions you need to login to an account (Piped or Invidious). Popular and Playlists work only with Invidious.

👍thank you
