### ISSUE TITLE
Thumbnails and subscriptions are not being displayed on my instance after making it private

### ISSUE THREAD

**Issue by sallyFoster** [yattee/yattee#788]
In order to access my instance now, a username and password are required. I added those in the link of Yattee but it is giving me errors

The instance is: https://bigspoon:1917@inv.altesq.net

![image](https://github.com/user-attachments/assets/9a18f131-56a9-40f7-9b43-c5d254b79919)

![image](https://github.com/user-attachments/assets/62c2f2b4-b7aa-4a40-830d-2c5f4e9a9e35)

![image](https://github.com/user-attachments/assets/8fe4284c-c6a6-4e1e-987f-29183d9bd4aa)

**Comment by stonerl** [comment]
Which version of Yattee are you running?

**Comment by stonerl** [comment]
Also, make sure your invidious proxy is properly configured. See [this comment](https://github.com/yattee/yattee/pull/762#issuecomment-2315716383).

**Comment by sallyFoster** [comment]
@stonerl The one in the App Store 
![image](https://github.com/user-attachments/assets/f32af396-28c7-4078-9f00-bad0ec672f53)

**Comment by stonerl** [comment]
You need the latest TestFlight version (193) for this to work.

**Comment by sallyFoster** [comment]
@stonerl How can I get access to that?

**Comment by stonerl** [comment]
https://github.com/yattee/yattee/wiki/Installation-instructions

**Comment by sallyFoster** [comment]
@stonerl 

So, I just the got the TestFlight version and still got the issue on the subscriptions 

![image](https://github.com/user-attachments/assets/f23485d5-8616-4f95-b1ac-46c27723a0e3)

**Comment by stonerl** [comment]
Have you configured your proxy as mentioned in the comment?

**Comment by sallyFoster** [comment]
@stonerl After configuring it, it works now, thanks a lot 🙏
