### ISSUE TITLE
Apple TV player stops video

### ISSUE THREAD

**Issue by Jeanmarchp** [yattee/yattee#79]
On long videos it will stop randomly playing video but audio continues. 

Recreation Steps:
- Open a long video
- Change quality to 1080p
- Wait till image freezes but audio continues.

**Comment by arekf** [comment]
There are problems with playing streams other than HLS and those marked as "stream". They shouldn't be really even included in the list as they are downloaded in full to be played but I left them for time being.

This will be mitigated with new player built on MPV.
