### ISSUE TITLE
[Request] distribute the yattee through AltStore

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#82]
This issue is to request for the possible distribution of the yattee app through the [Altstore](https://github.com/rileytestut/AltStore), an alternative app store for non-jailbroken iOS devices.

What I found in the Alstore [Readme.md](https://github.com/rileytestut/AltStore#readme), he began to support other developers to distribute their apps if they want to do it, in addition to the .ipa based install.

**Comment by arekf** [comment]
AltStore repostiory exists since always:
https://github.com/yattee/yattee/wiki/Installation-Instructions

**Comment by bachig26** [comment]
> AltStore repository exists since always: https://github.com/yattee/yattee/wiki/Installation-Instructions

No. It's not that, I knew about the this page.

This request is about the distributing the yattee app similar to Apple App Store inside the Altstore instead of sideloading.
![IMG_6499 (Edited)](https://user-images.githubusercontent.com/96393348/159691560-261e5aaa-13a4-4373-b946-e793fa2c1581.PNG)

**Comment by arekf** [comment]
This feature is not yet available with public AltStore release.
If you are paying for beta access with Patreon you get a build where you can add Yattee repo and see it listed in Browse section. 

I don't know when this feature will be available to public, I don't have control over AltStore.

**Comment by bachig26** [comment]
> This feature is not yet available with public AltStore release. If you are paying for beta access with Patreon you get a build where you can add Yattee repo and see it listed in Browse section.
> 
> I don't know when this feature will be available to public, I don't have control over AltStore.

oh okay. i didn't know this.
thank you.

**Comment by r0bbie** [comment]
Would also love to see Yattee added as a trusted source on AltStore! By a long way the app I have most need for sideloading on iOS, and AltStore would be by a long way my preferred way to do it.. (either once they finally allow alternative repos in the free and open source version, or yeah preferably with AltStore actually being added as trusted source!)

See you opened a related issue on the AltStore repo already @bachig26 :) rileytestut/AltStore#994
