### ISSUE TITLE
AltStore PAL Not working 

### ISSUE THREAD

**Issue by Zoriot** [yattee/yattee#826]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

![image](https://github.com/user-attachments/assets/fc379e2f-6c04-4dc0-8108-74a328b2a980)
Altstore PAL (EU) isn’t working, like I thought according to the Readme.

### Expected Behavior

Altstore PAL add the source and install the app. 

### Device & OS Version

iPhone 14, iOS 18

### App Build

_

**Comment by stonerl** [comment]
Not a bug in Yattee. AltStore PAL and AltStore work differently. You cannot add a AltStore source to AltStore PAL.

**Comment by Zoriot** [comment]
Will AltStore PAL not be added as a supported was to install the app? @stonerl

**Comment by Zoriot** [comment]
Thanks a lot for your help!
