### ISSUE TITLE
macOS thumbnails missing

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#827]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

![Screenshot 2024-09-24 at 19 55 41](https://github.com/user-attachments/assets/491a5050-667e-480a-9d35-ceeef566915b)

### Expected Behavior

Videos work fine with latest Invidious docker and fix, Invidious web has thumbnails but no Yattee.

I have not had the chance to test on iOS and tvOS yet.

### Device & OS Version

macOS 15

### App Build

196

### App Settings

Nothing fancy

**Comment by bbsixzz** [comment]
Same on iOS

**Comment by gigq** [comment]
Same here, macOS, iOS, Apple TV. Tried changing the quality of the thumbnails thinking lower quality might come through but nothing loads.

**Comment by gigq** [comment]
@bbsixzz Take a look at these settings in the config file, fixed the issue for me: https://github.com/yattee/yattee/issues/725#issuecomment-2293501428

**Comment by bbsixzz** [comment]
Thank you!

After changing the new config I forgot to set these:

```
external_port: 3000
domain: 10.0.1.2
```

I run it locally behind WireGuard so no external port open to the web.
