### ISSUE TITLE
[Bug] [iOS] Subscribe & Unsubscribe button not working properly

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#84]
The Subscribe & Unsubscribe button is not working with just one click to add or remove the channels for subscriptions.

### Current Behaviour:
The Subscribe & Unsubscribe button needs to be pressed/ clicked 2 to 3 times and sometimes more than 4 times to make this function work.

### Expected Behaviour:
The Subscribe & Unsubscribe button needs to work with just one click as indented, to add or remove the desired channel for the Subscriptions tab.

yattee version: v1.3.2
iOS version: 15.4

**Comment by arekf** [comment]
Cannot reproduce, can you provide more details?

https://user-images.githubusercontent.com/367484/160240760-5a98ca07-d917-49e0-9337-1400b1fbf4d6.mp4

**Comment by bachig26** [comment]
> Cannot reproduce, can you provide more details?

the subscribe/unsubscribe button while video playback like in your video works for me too. 
but ut doesn’t work via button provided after you get the search results and via channel view after opening the channel from search field.
![194D04B7-A70E-4893-BD13-195D0A24C53F](https://user-images.githubusercontent.com/96393348/160241110-95511931-493c-46d5-88a4-df186f088522.jpeg)

in this Image, you’ll see the unsubscribe button, I tried more than 20 times to unsubscribe but it doesn’t work, even after multiple restart.

**Comment by arekf** [comment]
Thanks. Requests to subscribe/unsubscribe channel endpoints are slow and after sending that it takes a few seconds for Piped to process the changes. I've changed the button to be disabled while this is happening.

Build with recent fixes will be available most probably tomorrow.
