### ISSUE TITLE
[Bug | Enchancement] „Back to Top“ implementation

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#85]
There is no „**Back to Top**“ function in the yattee, which would helpful instead of scrolling back to the top after browsing down the „**Subscription, Popular, Trending, Playlists“ Tab** and wherever possible.

with present state, it is frustrating to scroll back to top manually.

### Expected/ Desired Behavior:
 
**Double-tab the active or present tab (example: subscription tab) to go back to the top of the page.**

yattee version: v1.3.2
iOS version: 15.4

**Comment by arekf** [comment]
iOS has builtin system wide gesture to do exactly that -  tap the system clock.

**Comment by bachig26** [comment]
> iOS has builtin system wide gesture to do exactly that - tap the system clock.

Okay. It works.

But if I have a gps based app at background, it only switches back to that app, it is problem at that point.
