### ISSUE TITLE
[Bug | Enhancement] {iOS} Framerate drop during video playback

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#92]
The framerate or the resolution of the video drops significantly during the video playback even the quality defined to a particular one _(example: 720p, 60fps or 1080p, 60fps; Piped)_.
This issue happens more frequently.

_I have also checked everything on my end like internet speed and such, but it's good here. also, the official youtube, via piped instances or invidious in the browser works as expected._

**Comment by arekf** [comment]
This has been reported multiple times - see #35 #79

This is planned be improved with v1.4
