### ISSUE TITLE
[Bug | Enhancement] {iOS} minimize Keyboard with touch instead of return key

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#96]
This issue is to make enhancement to the minimizing of the keyboard after tapping the search field.

### Current Behaviour:
In order to close or minimize the keyboard after pressing the search field, the user needs to press the return key on the keyboard.

### Expected Behaviour:
The expected enhancement is by tapping anywhere outside the search field and the keyboard executes the closing or minimizing of the keyboard.

![IMG_6528](https://user-images.githubusercontent.com/96393348/160301324-8620b1d1-d4c5-4d5f-827e-b7275587bc19.PNG)

**Comment by arekf** [comment]
Scrolling view dismisses keyboard, closing
